### ISSUE TITLE
Inexpressible durations crash export to musicxml

### ISSUE THREAD

**Issue by mscuthbert** [cuthbertLab/music21#1022]
**music21 version**

v7 dev

**Problem summary**
Inexpressible durations are not divided into tied versions of themselves when converting to MusicXML, but instead crash.

**Steps to reproduce**
note.Note(quarterLength=80).write('musicxml')

**Expected vs. actual behavior**

Expected:  Note to be divided at every breve length or so into tied notes.

V6 behavior:  Incorrect musicxml is generated (with type "inexpressible") but remainder of score is outputted.

Actual behavior: Crash on musicxml export

**Comment by jacobtylerwalls** [comment]
makeTies assumes there is enough headroom to the right. Works if you put in a flat stream because making measures will fix it up:

```
>>> from music21 import *
>>> n = note.Note(quarterLength=80)
>>> s = stream.Stream(n)
>>> s.show()
```
![Screen Shot 2021-05-17 at 8 52 52 AM](https://user-images.githubusercontent.com/38668450/118491730-4836fe00-b6ed-11eb-971a-a45bc4fdeda4.png)


https://github.com/cuthbertLab/music21/blob/753f47fe2595f7b0364b969c0de7059d4383caf1/music21/stream/makeNotation.py#L964-L967


Do you want to support this case with an enhancement to makeTies?

**Comment by jacobtylerwalls** [comment]
or, if all we care about is fromNote, we can have fromNote call makeMeasures to get measures, instead of creating a single measure and letting that be a constraint on makeTies.
