### ISSUE TITLE
How to implement performance properties like dynamics, rubato?

### ISSUE THREAD

**Issue by Chiel92** [cuthbertLab/music21#103]
Say I have a piece encoded in music21 objects. If I export this to midi and play through a synthesizer,
I find that the performance is very flat and static. I would like to programmatically add a few enhancements, such has 

- sustain, by prolonging all currently playing notes, until an explicit cut-off
- rubato, by slowing down the tempo at the start of each measure
- dynamics, by increasing the volume of notes that are *on* the beat, or by decreasing notes that are short and/or *off* the beat

Is this possible to do within music21, and if yes, what would be the right way to go about it?

**Comment by mscuthbert** [comment]
Hi Chiel92 -- yes, these should be possible to implement since we have all of the data, but it's not something that we do now and would probably take someone who really wants to work on human-style playback and has a month or so to implement.  For now, the best thing would be to export the midi file and then to rework it into a synth program or notation program (such as Finale) that already has the skills to do this.  It'd be a big addition -- nice to have but not on the core priority list.

**Comment by Chiel92** [comment]
Would the result again be a (enhanced) midi file?
I would like to have that, to make it possible to use any kind of synthesizer.

**Comment by mscuthbert** [comment]
I believe you can export to enhanced MIDI from most of those software packages.

Best,
Michael

---
Sent from a phone (413-575-6024)
Apologies for typos or general brevity

On Sep 14, 2015, at 15:27, Chiel <notifications@github.com<mailto:notifications@github.com>> wrote:


Would the result again be a (enhanced) midi file?
I would like to have that, to make it possible to use any kind of synthesizer.

**Comment by mscuthbert** [comment]
I will close this for now seeing that there's not a programmer volunteering to implement it.  It can be reopened.
