### ISSUE TITLE
Transposing instrument part (atSoundingPitch==True) not shown in written pitch

### ISSUE THREAD

**Issue by gregchapman-dev** [cuthbertLab/music21#1039]
**music21 version**

`7.0.6a1+PR996`   

**Problem summary**
score.show('musicxml.pdf') of a score containing transposing instruments (with part.atSoundingPitch set to True) exports with sounding pitch being written instead of written pitch.

See code example below...

```
Paste minimal code example here. Most issues can be reproduced with just a few elements.
Attach external files only after attempting to reproduce using a simple stream.

import music21

inst = music21.instrument.Instrument('madeUpInstrument')

# instrument transposes by 1 "letter" (generic 2nd), 2 semitones (2 chromatic steps)
inst.transposition = music21.interval.intervalFromGenericAndChromatic(2, 2)
part = music21.stream.Part()
part.atSoundingPitch = True
part.insert(0, music21.clef.TrebleClef())
part.insert(0, music21.key.KeySignature(sharps=-1)) # sounding key = 1 flat
part.insert(0, music21.note.Note('C4')) # sounding note = middle C
part.insert(0, inst)

score = music21.stream.Score()
score.insert(0, part)

# the following should display a B-flat (key = 3 flats).
# Instead it displays a C (key = 1 flat).
score.show('musicxml.pdf')

part.toWrittenPitch(inPlace=True)

# now it's right
score.show('musicxml.pdf')
```

**Expected vs. actual behavior**

See code snippet.

**More information**

macOS Big Sur, using MuseScore for showing scores.

**Comment by jacobtylerwalls** [comment]
Couple things going on:
 - we were returning early instead of writing a `<transpose>` tag when we had `True` for `.atSoundingPitch`. Until MusicXML 4.0 came out a few days ago, we had no choice: all scores are in written pitch. So that wasn't quite right.
 - also, there are some recursion problems in `.toWrittenPitch()` when called on Parts, see this case:

```
>>> from music21 import *
>>> p = stream.Part(stream.Measure([instrument.Clarinet(), note.Note()]))
>>> p.atSoundingPitch = True
>>> p.toWrittenPitch().show('t')
{0.0} <music21.stream.Measure 0 offset=0.0>
    {0.0} <music21.instrument.Clarinet 'Clarinet'>
    {0.0} <music21.note.Note C>
```

The net effect of these two issues was probably to cancel each other out UNTIL you toggled the concert pitch controls in a musicxml reader.

We can fix these, and then sometime next year see about getting support for the [new](https://www.w3.org/2021/06/musicxml40/musicxml-reference/elements/concert-score/) `<concert-score>` tag. Thanks for the report!
