### ISSUE TITLE
Installation guide is not good

### ISSUE THREAD

**Issue by AlmogCohen** [cuthbertLab/music21#104]
Hi, reading your installation guide here made me very scared!
http://web.mit.edu/music21/doc/installing/installMac.html#installmac

But in order to install the latest music21 package all someone has to do is:
`pip install https://github.com/cuthbertLab/music21/releases/download/v2.0.8/music21-2.0.8.tar.gz`

Consider remaking things to look more natural, the documentation is very scary while the real installation process is a piece of cake.

**Comment by mscuthbert** [comment]
Hi Almog -- `pip` is not installed by default on the Mac, so unfortunately the guide can't be paired down to just that.

btw -- you should be able just to type `pip install music21` and it will get the latest release.

**Comment by AlmogCohen** [comment]
Ok cool :)
By the way, untill last week when running pip install the installed version
was 2.0.5 for my windows and not 2.0.8

**Comment by mscuthbert** [comment]
That's understandable since v2.0.8 was only released last week.  :-)  I believe it should work now.

I'll keep working on making the install guide simpler.  Unfortunately there are many different systems so we've tried a bit of a kitchen sink approach to make sure things still work on many older macs.
