### ISSUE TITLE
Numeric Tempo

### ISSUE THREAD

**Issue by daniel-portia** [cuthbertLab/music21#1047]
**music21 version**

`6.7.1`   

**Problem summary**
I am not able to extract the numeric tempo from an xml file produced in Finale.

**Steps to reproduce**

```
score = music21.converter.parse(file_path)
print(score.beat)

```

**Expected vs. actual behavior**
I would expect to find in the "beat" property the numeric tempo I can see in the xml file.
If that's not the proper way to obtain the numeric tempo, I would like to know how to do it.

**More information**
In the .xml file, the numeric tempo appears in the 1st measure of the 1st part in the element "sound" (under the "direction" element) containing the "tempo" property. See example below:

```
<?xml version='1.0' encoding='UTF-8' standalone='no'?>
<!DOCTYPE score-partwise PUBLIC "-//Recordare//DTD MusicXML 3.1 Partwise//EN" "http://www.musicxml.org/dtds/partwise.dtd">
<score-partwise version="3.1">
...
<part id="P1">
    <?SmartMusic maxVoice=2?>
    <measure number="1" width="242">
      ...
      <direction placement="above">
        <direction-type>
          <words default-x="79" default-y="37" font-size="11.9" font-weight="bold">Andante</words>
        </direction-type>
        <sound tempo="76"/>
      </direction>
       ...
```

**Comment by jacobtylerwalls** [comment]
Stream.beat [returns None](http://web.mit.edu/music21/doc/moduleReference/moduleStream.html?highlight=beat#music21.stream.Stream.beat) because the beat property refers to the position of an element in a stream, given a meter, and doesn't make sense for streams themselves.

You'll want to look for Tempo.MetronomeMark objects in your score. You can do a recursive search to make sure you visit any parts or measures that might have tempo objects:

```
>>> s.recurse().getElementsByClass('MetronomeMark')[0]
<music21.tempo.MetronomeMark adagio Quarter=56.0>
>>> s.recurse().getElementsByClass('MetronomeMark')[0].number
56.0
```

Or:
```
>>> s.flat.next('MetronomeMark')
<music21.tempo.MetronomeMark adagio Quarter=56.0>
>>> s.flat.next('MetronomeMark').number
56.0
```

From your excerpt I cannot see if there is also a `<metronome>` tag. Currently music21 only parses `<metronome>`, i.e. the visual mark, not `<sound>`, the playback control. See #159 where that work is tracked. In essence, if your excerpt has `<metronome>`, you're in luck; otherwise we are waiting on a patch for #159. Hope that helps.
