### ISSUE TITLE
Support common vocal-synthesis file types (vsqx, ust, vog)

### ISSUE THREAD

**Issue by oxygen-dioxide** [cuthbertLab/music21#1092]
**Motivation**

As a music producer, I hope that after inputing a piece of sheet music into music21, my computer can not only play it but also sing it to me. This is useful when arranging acapella.

**Feature summary**
Supporting importing and exporting common vocal-synthesis file types, including vsqx, ust and vog files

**Proposed implementation**
Vsqx is the file type of vocaloid4. It is based on xml.
Ust is the file type of utau. It is based on ini.
Vog is the file type of [vogen](https://github.com/aqtq314/Vogen.Client), an open-source AI vocal synthesizer. It is based on compressed json. I am developing a python implemention of vogen called "[PyVogen](https://github.com/oxygen-dioxide/vogen)"

**Intent**

- [x] I plan on implementing this myself.
- [ ] I am willing to pay to have this feature added.
- [x] I am starting a discussion with the hope that community members will volunteer their time to create this. I understand that individuals work on features of interest to them and that this feature may never be implemented.

**Comment by mscuthbert** [comment]
What would be the advantage of doing this in music21?  Since I've never heard of any of these three formats and I'd be having to maintain the code to support them for the long-term future, I'm slightly -1 on the idea as opposed to building a separate library that imports music21 to do this conversion.  Can you explain more why this needs to be in the music21 library?

**Comment by oxygen-dioxide** [comment]
For anyone who wants to convert between music21 objects and singing synthesis file formats, I'm developing https://github.com/oxygen-dioxide/music21-svs-formats
