### ISSUE TITLE
how to get the layout information of 'rest'?

### ISSUE THREAD

**Issue by YolandaFeng1995** [cuthbertLab/music21#1122]
as said in the title

**Comment by jacobtylerwalls** [comment]
Hi YolandaFeng. This forum is for bug reports and enhancement proposals. If you have usage questions, see the music21 mailing list (linked from project homepage) where users help each other with questions like this. You would probably want to explain what you mean by layout, since it's not clear to me.

**Comment by YolandaFeng1995** [comment]
it means style information. e.g. absolute-X?

**Comment by jacobtylerwalls** [comment]
Just like note objects, rests have a `Style` object stored on the `.style` attribute, so access `.style.absoluteX`.
