### ISSUE TITLE
Improved metadata

### ISSUE THREAD

**Issue by gregchapman-dev** [cuthbertLab/music21#1139]
**Motivation**
A lot of metadata in various music file formats and in various standard metadata formats is currently not imported into, or exported from music21.

**Feature summary**
I am most familiar with the Humdrum file format's metadata, so I will use that as an example.  But there are many other metadata formats in many other file formats.  

1. Humdrum has a series of standard 3-char codes (keys) for things like title (OTL), composer (COM), etc.  
e.g. '!!!COM: Ludwig von Beethoven'.  Some of these are already supported by music21, but many are not.  We could simply add the rest of them, or (better) do something smarter.

2. Humdrum also supports the following two variations on the 3-char-code (key) scheme, for localized text:
'!!!OTL@FR: Le titre de la chanson' (single @ means this is the actual original title)
'!!!OTL@@RU: название песни' (double @@ means this is a translated title) <-- 'ru' should capitalized, don't know what happened there.
music21's metadata carrying capability should be enhanced to support this.

3. Humdrum also supports any other key/value pairs, with keys of any length, that the editor is free to make up, for example:
'!!!excerpt-start-measure: 24'

I have been pointed at music21.editorial.Editorial, which is interesting, but it currently has only .comments and .footnotes, with no key/value pairs, and no localization.

The current metadata implementation appears to be closely related to Humdrum metadata, and the current editorial implementation appears to be closely related to MusicXML's footnote capability.  Perhaps the best approach might be to take some example metadata formats that are in current use by musicologists/encoders/librarians (perhaps from music file formats like MEI, perhaps in sidecar files with metadata-specific formats), and see what features would be worth supporting.  Perhaps we need plugins for metadata import/export, like we have for music?

Let's discuss!

**Proposed implementation**
Too soon for any proposals, we need to discuss first.

**Intent**

[x ] I plan on implementing this myself, perhaps with others.
[ ] I am willing to pay to have this feature added.
[ ] I am starting a discussion with the hope that community members will volunteer their time to create this. I understand that individuals work on features of interest to them and that this feature may never be implemented.

**Comment by jacobtylerwalls** [comment]
Happy to continue discussing, and to stay focused on Metadata; but for Editorial, just want to point out it does support arbitrary key-value pairs:
```
>>> s = stream.Score()
>>> s.editorial
<music21.editorial.Editorial {}>
>>> s.editorial.whatever = 'yeah'
>>> s.editorial.whatever
'yeah'
```

**Comment by gregchapman-dev** [comment]
Good grief! I totally missed that it inherits from dict.  Duh.

In any case, I really do want to help music21 support standard metadata such as RDL or MARC, and I’m very interested in what MEI does: 

"MEI’s approach to metadata is heavily influenced by other existing standards and models, such as TEI, MARC, and FRBR. It attempts to reflect both current library practice and common scholarly methods…”
— from https://music-encoding.org/guidelines/v4/content/metadata.html <https://music-encoding.org/guidelines/v4/content/metadata.html>

Off to do some reading about these various metadata standards.

Greg

**Comment by mscuthbert** [comment]
RDL is dead, so let's forget that.  I meant RDF. But it's way too complicated to implement and use.  

TEI is too specific to the digital humanities field (and not standardized enough) to make it the main format.  I didn't know about FRBR but it also has far lower hits than MARC.

But then I remembered: Dublin Core -- that's the metadata standard that is closest to how music21 is already storing data (Contributors, etc.) -- that's probably the main first one to hit.

MEI has some great metadata standards -- the main thing in CWMN that recommends it over MusicXML -- and there are some tools for extracting them, so it's a possibility I'd consider having the `music21` names more closely resemble for entities that we do not already have.

However, there is a music21 way of associating metadata with a particular movement, score within an opus etc: just insert another Metadata object in the appropriate place.  Metadata can go anywhere in a stream.  So that's the more idiomatic approach to relation-links between metadata and individual movements, for instance.    But most people set movementTitle instead.

I think that having a `qualifier` attribute (default None) could be a way of specifying that a title is only for a particular language or something.

**Comment by gregchapman-dev** [comment]
I forgot about DublinCore!  This is a great idea for a relatively simple enhancement with good payoff. 

I'll do some reading, and then come up with an object/API proposal to get us going.  

My goal would be to make the enhancement as backward compatible as possible (so I can get it into v7.x), but I'm keeping all options open at the moment (i.e. it might have to be a v8 thing).

**Comment by ahankinson** [comment]
One thing you might consider is expressing your metadata in JSON-LD. This way you can use any number of existing schemas, and can even mix and match them. You can, for example, use some terms from the Dublin Core vocabularies, and others from Schema.org.

JSON-LD has a fairly steep learning curve, but it plateaus quite quickly once you get the gist of it. The easiest way to figure out what it does is to play around with the JSON-LD playground.

Briefly: JSON-LD is "just" JSON, but it provides an `@context` which can be used to define the different metadata vocabularies you are using. When a browser, or any other key/value store (Python Dicts) interpret it, it works exactly like you would expect. However, when a JSON-LD processor encounters it, it expands the terms you define based on the `@context` you provide.

So looking at one of the examples for a "Library": https://tinyurl.com/55rdcy2s

If you click through the tabs at the bottom, you can see an option for a "Table" -- I find this is the easiest to understand. You'll see statements like this:

```
http://example.org/library/the-republic   |   http://purl.org/dc/elements/1.1/creator   |   Plato
```

This is interpreted from some JSON-LD that looks like this:

```
{
      "@id": "http://example.org/library/the-republic",
      "@type": "ex:Book",
      "dc11:creator": "Plato",
      "dc11:title": "The Republic",
      "ex:contains": "http://example.org/library/the-republic#introduction"
}
```

The `@context` block provides the magic here:

```
"@context": {
    "dc11": "http://purl.org/dc/elements/1.1/",
    "ex": "http://example.org/vocab#",
    "xsd": "http://www.w3.org/2001/XMLSchema#",
    "ex:contains": {
      "@type": "@id"
})
```

What this tells the JSON-LD processor is that whenever you see the `dc11:` prefix on a field, expand this to the full namespace for the element, e.g., `dc11:creator == "http://purl.org/dc/elements/1.1/creator"`. This tells you that this `creator` field is to be interpreted as a Dublin Core creator.

You can go one step further and change the context to even remove the prefix. If you insert the following into the context in the playground:

```
"creator": "dc11:creator",
```

and then edit the block in the body from `"dc11:creator": "Plato"` to `"creator": "Plato"`

Then this context change tells the processor that the `creator:` JSON key should be interpreted as a Dublin Core creator, and you don't need the prefix in the body of your JSON.

JSON-LD also helpfully provides a standardized mechanism for multi-lingual support using "Language Maps". In the same playground, add the following to the `@context` block:

```
"title": {
      "@id": "dc11:title",
      "@container": "@language"
    },
```

and then change the body from `dc11:title: The Republic` to:

```
title: {"en": ["The Republic"], "fr": ["Le Republique"]}
```

You will see in the table view that the 'language' column now has parallel titles in both French and English. The context change specifies that the vocabulary for the values is the Dublin Core title, but that there are multiple variants in different languages for this change.

---

This may be a bit too much to take in in one go, but perhaps one small consideration when designing your metadata improvements is to keep namespaces in mind. This will allow others to use *any* standard, as it fits their needs, simply by being very specific about which vocabulary defines the field that you are using. So instead of simply storing:

```
{
title: Moonlight Sonata,
creator: Ludwig v. Beethoven
}

You can store:

```
[{"ns": "http://purl.org/dc/elements/1.1/title",
"value": "Moonlight Sonata",
"lang": "en"
}, {
"ns": "http://purl.org/dc/elements/1.1/creator",
"value": "Ludwig v. Beethoven",
"lang": "@none" }]     // @none is a special value that indicates that there is no distinguishing language defined.
```

**Comment by gregchapman-dev** [comment]
Very interesting, thanks!

**Comment by gregchapman-dev** [comment]
Closing this to focus on a more detailed proposal in issue # 1262.
