### ISSUE TITLE
Fresh Installation with python 3.10

### ISSUE THREAD

**Issue by daniellumertz** [cuthbertLab/music21#1147]
I don't think this is really a music21 problem (maybe matplotlib?)**I just wanted to inform here so people know it**. I am installing music21 in a fresh python 3.10 with no other things. And it is getting a problem trying to install matplotlib. From what I understood It is thinking the python version installed is very old to match the requirements.  And keep in a loop trying to install matplotlib.
![image](https://user-images.githubusercontent.com/76976666/136610948-e593badf-3efc-4821-9cbf-1f0f7c56f181.png)
That is all . I don't think it is a music21 problem, but newcomers (like me) might  be having this problem while 3.10 still new (?)

I am also really new to python so I might messed up, sorry if it is the case. Just wanted to inform in case more people got the same problem. 

Sorry if this is the wrong place to post >.< if so where would be appropriate ?

**Comment by mscuthbert** [comment]
This is fine  to post here.  I'll leave it for a while until closing it -- you might post on the music21list mailing list as well since people might want to know this about 3.10 there as well and that gets a lot more readership than GitHub issues.

My CI (Github Actions) only started supporting Python 3.10 five days ago, so I haven't been rushing to make sure music21 totally works with it.  Even though I have reports that it does work with 3.10, I don't want to actively encourage using it until major players (matplotlib, tensorflow) release 3.10 compatible versions as well.  I still don't even have a fully working AWS 3.9 install!

**Comment by daniellumertz** [comment]
Thanks for the info! :D. I rolled back to 3.9.7, will wait a while to go to 3.10

**Comment by jacobtylerwalls** [comment]
Hi Daniel. Hope you're able to upgrade to Python3.10 as soon as the packages you use music21 with are ready to go. As Myke just explained on the Google list, all the bare minimum requirement packages are compatible at this point, so I'll be closing this GitHub issue. Cheers.
