### ISSUE TITLE
Part name and abbreviation not preserved after expanding repeats

### ISSUE THREAD

**Issue by DIDONEproject** [cuthbertLab/music21#1165]
**music21 version**
6.7.1

**Problem summary**
When expanding a score by using score.expandRepeats(), the p.partName attribute for all parts becomes a series of numbers and letters. For instance, the p.partName attribute for singer part "DIRCEA" becomes "0x2240c118088".
It might be a problem with memory allocation or an error during the copy of each part.
By doing some debugging, I got to find that this mislabelling occurs at line 800 in process() in repeat.py, when discriminating between having or not having Dacapo.
When creating a new object at line 1847,
 # process measures
        new = streamObj.__class__()

the new object takes everything from the previous object but the name is already changed. Obviously, this becomes a problem when trying to use these new expanded parts, although the expansion of repetitions works fine.

**Expected vs. actual behavior**
expanded parts should preserve the name to be able to be used later in the same way as non-expanded parts.

I would be really thankful if you could throw some insight on this, either just checking if this is happening to other users or if there is sth we are doing wrong when expanding repeats.

Thank you very much in advance, 
keep in touch!

**Comment by jacobtylerwalls** [comment]
Thanks for the report, that looks like something we should fix!

I reproduced like this:

```python
>>> p = converter.parse('tinyNotation: c1 d e f')
>>> p.measure(2).storeAtEnd(bar.Repeat(direction='end', times=1))
>>> p.partName = 'mypartname'
>>> exp = p.expandRepeats()
>>> exp
<music21.stream.Part 0x7fc5c0135760>
>>> exp.partName is None
True
```

Can you let us know whether the `partName` of your source is set on the Part object or on an Instrument object? Since `partName` is a property, my guess is that this is only a problem with `_partName` private attribute of the Part object. (As well as `_partAbbreviation`.)

**Comment by DIDONEproject** [comment]
Hey! Thanks for taking a look at it so quickly.
I would say we set the partName attribute in the part object, since I get the parts when running:
`list(score.instruments)[0].partName `(for the first part)
but I get an empty list when running: list(score.getInstruments())
Just let me know if you need any further info

**Comment by TAnas0** [comment]
Should this be labelled as a "verified bug"?

**Comment by kir12** [comment]
Hi, I came across this issue and am interested in working on it and have a quick question. I wanted to see if any test cases for this function fail because of the bug, so I examined the [documentation for expandRepeats()](https://web.mit.edu/music21/doc/moduleReference/moduleStreamBase.html?highlight=expandrepeats#music21.stream.base.Stream.expandRepeats) and it indicates that doc tests need to be written for the method. (namely the text `TODO: DOC TEST`) Double-checking the `expandRepeats()` source code confirmed this, but I was also unable to find any module-level test cases for `expandRepeats()` inside `stream`'s `tests.py`. Might there be another location where test cases for this function are stored? And if no test cases exist for this method, would the code snippet @DIDONEproject be a good start? 

(I'm asking primarily because the developer docs indicate that all pull requests must have tests)

**Comment by jacobtylerwalls** [comment]
Terrific. Yeah, a unit test at the bottom of repeat.py will do just fine.

> While we're on the topic of expandRepeats, should we also go ahead and create doc tests for the method too?

Also great to have. Could you open that as a separate PR? That way one or the other can move faster. Thanks!
