### ISSUE TITLE
copies of elements appear "in" Streams

### ISSUE THREAD

**Issue by mscuthbert** [cuthbertLab/music21#123]
Is this right?

```python
import copy
n = note.Note()
s = stream.Stream()
s.append(n)
n2 = copy.deepcopy(n)
assert n2 in s
```

This seems wrong to me, but it has major consequences potentially to changing it.

**Comment by mscuthbert** [comment]
Stream has no __contains__ -- potentially meaning that a StreamIterator is being created where one doesn't need to be.

**Comment by shimpe** [comment]
It's a matter of interpretation of what "in" means.

```
import copy
l = [ (0,0), (1,1) ]
e = copy.deepcopy(l[0])
e is l[0]  # returns True
e == l[0] # returns True
e in l # returns True

l = [ [0,0], [1,1] ]
e = copy.deepcopy(l[0])
e is l[0] # returns False
e == l[0] # returns True
e in l # returns True
```

I think the difference in behavior is caused by tuples being immutable, while lists are mutable. 
As a side-effect it neatly demonstrates that apparently the "in" operator uses == instead of "is" for comparisons. That seems to be consistent with the note-in-stream behavior you considered wrong. 
At least it seems consistent with the rest of Python.

**Comment by mscuthbert** [comment]
Ah. If "n == n2" then the behavior is correct. I am away from wifi so I can't check.

**Comment by mscuthbert** [comment]
Indeed -- 5 months later, I see that `n == n2` so this is correct.  Thanks @shimpe !
