### ISSUE TITLE
transposition problem

### ISSUE THREAD

**Issue by shimpe** [cuthbertLab/music21#124]
Code:

import music21
music21.interval.transposePitch(music21.pitch.Pitch("c"), music21.interval.ChromaticInterval(5))

Result: 

Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "/usr/lib/python3.5/site-packages/music21-3.0.2-py3.5.egg/music21/interval.py", line 2367, in transposePitch
    interval1.diatonic.generic.staffDistance)
AttributeError: 'ChromaticInterval' object has no attribute 'diatonic'

(similar to another transposition problem involving ChromaticInterval I once reported)

**Comment by mscuthbert** [comment]
Note the docs -- you need to give an interval.Interval() object, not a class such as ChromaticInterval or DiatonicInterval.  Simply create an interval.Interval(5) object instead of interval.ChromaticInterval(5) object.  This will work fine.

Alternatively, call interval.ChromaticInterval(5).transposePitch(pitch.Pitch('C')).

However, there may be an easy way to make it work properly (in the latest commit). But not a bug since the docs already specified that it must be an interval.Interval object.

**Comment by shimpe** [comment]
Ok, I'm sorry. You're right of course I had somehow assumed that both ChromaticInterval and DiatonicInterval were derived from Interval, but instead Interval encapsulates both a ChromaticInterval and a DiatonicInterval. Thanks for the clarification.

**Comment by mscuthbert** [comment]
No problem.  I believe it works now either way, in any case.
