### ISSUE TITLE
stripTies() exception with chord symbols in v7.3.3

### ISSUE THREAD

**Issue by xavriley** [cuthbertLab/music21#1294]
**music21 version**

Issue is present on `7.3.3`, but not on `'6.7.1'`. Looks like a regression.

**Problem summary**

When calling `.stripTies()` on a score imported from MusicXML, an exception occurs when a tie over a barline has a chord symbol on the "stop" note. E.g. for this score 

![image](https://user-images.githubusercontent.com/369527/167020306-c826a996-34e7-4052-a36e-5dc054c4b3cb.png)

calling `x.stripTies()` fails with:

```
>>> x.stripTies()
 Traceback (most recent call last):
   File "<stdin>", line 1, in <module>
   File "/Users/xavriley/opt/anaconda3/envs/qparse/lib/python3.9/site-packages/music21/stream/base.py", line 7126, in stripTies
     p.stripTies(inPlace=True, matchByPitch=matchByPitch)
   File "/Users/xavriley/opt/anaconda3/envs/qparse/lib/python3.9/site-packages/music21/stream/base.py", line 7312, in stripTies
     raise StreamException('aggregated ties have a zero duration sum')
 music21.exceptions21.StreamException: aggregated ties have a zero duration sum
```

Removing the chord symbol in the second bar ("Bb7") allows `stripTies()` to succeed.

**Steps to reproduce**

I did try to reproduce this using tiny notation but as far as I can tell, it only happens with a score from a MusicXML source.

A minimal XML example is available here: https://www.dropbox.com/s/xce206n23by2a3m/stripTiesBug.xml?dl=0. Loading it with

```
from music21 import *
x = converter.parse("/path/to/stripTiesBug.xml")
x.stripTies()
```

is enough to reproduce the issue.

Strangely, the following tinyNotation produces the same stream but *does not* raise an exception.

```
myStream1 = m21.converter.parse('tinynotation: 4/4 C.4 C8 F.4 B-8~ | B-8 B-8 D4 G4 F4')
myStream1.measures(0, None)[0].insert(0, m21.harmony.ChordSymbol('C7'))
myStream1.measures(0, None)[0].insert(2, m21.harmony.ChordSymbol('F7'))
myStream1.measures(0, None)[1].insert(0, m21.harmony.ChordSymbol('B-7'))
myStream1.stripTies()
```

**Expected vs. actual behavior**

`stripTies()` should work when chord symbols are present.

**More information**

As a workaround, removing the chord symbols seems to allow `stripTies()` to work e.g.

```
for c in x.recurse().getElementsByClass(m21.harmony.ChordSymbol):
    x.remove(c, recurse=True)

x.stripTies() # succeeds
```

**Comment by jacobtylerwalls** [comment]
Thanks for the report. A workaround is to pass `matchByPitch=False` to stripTies (notes and chordsymbols are both GeneralNote subclasses, so here they "match pitch" and an attempt is made to bridge them). We changed the default of `matchByPitch` to be True in v7, so it's likely the issue did exist before.

> Strangely, the following tinyNotation produces the same stream but does not raise an exception.

`measures()` returns a ` Score`, so it looks like you're inserting the symbols into the Part, not the Measure, which would lead to different results.

In terms of defining the correct behavior, I guess the simple solution is to just completely ignore ChordSymbols in stripTies(), since they shouldn't be tied, normally. (But perhaps we should still include them if `.writeAsChord=True`?)

Would you like to investigate and propose a patch?

**Comment by xavriley** [comment]
Cool thanks for the clarification. I'll have a go at writing up a PR 👍
