### ISSUE TITLE
RomanNumeral: secondary vi and vii

### ISSUE THREAD

**Issue by malcolmsailor** [cuthbertLab/music21#1353]
**music21 version**

`8.0.0a3`   

**Problem summary**

In secondary roman numerals in minor keys, when the secondary key is minor, vi and vii don't behave according to the sixthMinor and seventhMinor flags to RomanNumeral. Not sure if this is expected behavior, but it surprised me.

**Steps to reproduce**

```
>>> from music21 import roman
>>> RN = roman.RomanNumeral
>>> from functools import partial
>>> rn = partial(RN, sixthMinor=roman.Minor67Default.FLAT, seventhMinor=roman.Minor67Default.FLAT)
>>> rn("V/vi", "c").pitches # expect Eb G Bb
(<music21.pitch.Pitch E5>, <music21.pitch.Pitch G#5>, <music21.pitch.Pitch B5>)
>>> rn("V/vii", "c").pitches # expect F A C
(<music21.pitch.Pitch F#5>, <music21.pitch.Pitch A#5>, <music21.pitch.Pitch C#6>)
>>> rn("V/VI", "c").pitches # OK
(<music21.pitch.Pitch E-5>, <music21.pitch.Pitch G5>, <music21.pitch.Pitch B-5>)
```

**Comment by mscuthbert** [comment]
Ah, we are likely not passing sixthMinor or seventhMinor on to the secondary RN.  That’s a bug. that should be easy to fix.  Will make a patch.

On Aug 5, 2022, at 07:21, malcolmsailor ***@***.******@***.***>> wrote:



music21 version

8.0.0a3

Problem summary

In secondary roman numerals in minor keys, when the secondary key is minor, vi and vii don't behave according to the sixthMinor and seventhMinor flags to RomanNumeral. Not sure if this is expected behavior, but it surprised me.

Steps to reproduce

>>> from music21 import roman
>>> RN = roman.RomanNumeral
>>> from functools import partial
>>> rn = partial(RN, sixthMinor=roman.Minor67Default.FLAT, seventhMinor=roman.Minor67Default.FLAT)
>>> rn("V/vi", "c").pitches # expect Eb G Bb
(<music21.pitch.Pitch E5>, <music21.pitch.Pitch G#5>, <music21.pitch.Pitch B5>)
>>> rn("V/vii", "c").pitches # expect F A C
(<music21.pitch.Pitch F#5>, <music21.pitch.Pitch A#5>, <music21.pitch.Pitch C#6>)
>>> rn("V/VI", "c").pitches # OK
(<music21.pitch.Pitch E-5>, <music21.pitch.Pitch G5>, <music21.pitch.Pitch B-5>)
