### ISSUE TITLE
Mid-measure repeats

### ISSUE THREAD

**Issue by MarkGotham** [cuthbertLab/music21#1383]
**Motivation**

Music21 shares in a wider issue (e.g., with musicXML) in handling mid-measure repeats.

As @mscuthbert says in #858:

> Most music representation isn't prepared to have repeat signs inside a Measure -- as represented even if not as conceived, so something like:
> 
> 4/4 Q | Q Q Q Q | Q Q Q :|| Q | Q Q Q Q | etc.
> 
> is generally represented as:
> 
> 4/4 m0 | m1 | m2a :|| m2b | m3 | etc.
> 
> where there is NO mid-measure repeat, but instead two measures both called "measure 2", probably (in m21) with m2a's .paddingRight = 1.0 and m2b's .paddingLeft = 3.0 (same as m0) to set the beat counts properly in the two.

**Feature summary**

TODO:
- (policy on how to) handle mid-measure repeats/barlines in general within music21. (Note gaps between musicXML, MuseScore, etc.)
- parsing/outputting mid-measure repeats in romantext and any other relevant import/export formats originating and maintained here.

**Proposed implementation**

TBD

**Intent**

I'm happy to do / be a part of the dev. First, we need to agree an approach (and the more voices there the merrier).

**Comment by mscuthbert** [comment]
Hi Mark -- I know you're trying to help, but this issue is too vague to be useful or to ever close.  Can you change this to a tracking issue of specific places where you want mid-measure repeats to be more functional?  Music21 **has** mid-measure repeats:

```
m = stream.Measure([
    note.Note('C'),
    bar.Repeat('start'),
    note.Note('D'),
    bar.Repeat('end'),
    note.Note('E'),
])

m.show('text')
{0.0} <music21.note.Note C>
{1.0} <music21.bar.Repeat direction=start>
{1.0} <music21.note.Note D>
{2.0} <music21.bar.Repeat direction=end>
{2.0} <music21.note.Note E>
```

so some possible issues might be (in order of difficulty, and probably in the order they'd need to be solved):
* parse mid-measure repeats in RomanText
* export mid-measure repeats in RomanText
* split measures at mid-measure repeats
* automatically rejoin measures split at mid-measure repeats after expanding
* RepeatExpander expand mid-measure repeats
* use new rejoin system to allow mid-measure repeats to be exported from musicxml.  

and once the issues have been thought through, consider whether they're worth the time to implement rather than using `m16a:, m16b:` in RomanText or automatically splitting the measures there too.

One thing that made early versions of music21 so slow (to run and to develop) was trying to encode every possible way of looking at music that musicians use into a computer-processed system.  (MEI has, in my opinion, the same worthwhile goal and same drawbacks because of it).  We're still dealing with the negative consequences of that initial choice in areas like `pitch.accidental == None` being different than `pitch.accidental == Accidental('natural')` because I wanted to represent notions from Gregorian chant scholarship/representations.  (thankfully the initial notion that a pitch might have multiple accidentals with different traditions/probabilities, was dropped long before music21 v1). 

So while you and I know that a measure can have a repeat within it, or can change time signature in the middle of it, etc., is it worth encoding this to the computer, or would it be easier to add an editorial attribute to Measure "conceptuallyPartOfPrevious = True" and when people want to work with this issue they can do that?

**Comment by MarkGotham** [comment]
Thanks @mscuthbert  and fair enough. Excuse my half-baked first attempt (and now also the slow reply). Put both down to having lots of enthusiasm (yes, keen to help!) but not so much time.

I'm also seeking to keep track of (open) TODOs that risk getting lost in (closed) issues.

I'll try again with a new issue on 'Stream-stream alignment'.

As you suggest, whatever we do on romantext specifically, there will still be divergences of this kind. That being the case, it would be useful to create some functionality that would deal with the worst of that - something similar to the wonderful `template` function (for creating a new stream with important information from an existing one) but here for adjusting one stream to match another.

**Comment by mscuthbert** [comment]
Thanks Mark -- in other projects I have a "closed_but_useful" tag.  I'll make one and apply it to this.
