### ISSUE TITLE
Rntxt repeats duplicating time signatures (from comment on #1387)

### ISSUE THREAD

**Issue by MarkGotham** [cuthbertLab/music21#1392]
**Motivation**

Rntxt repeat functions duplicates time signatures. For example, `testCase = converter.parse('romantext: m1 I\nm2=m1')` results in:

<img width="433" alt="TS_repeat" src="https://user-images.githubusercontent.com/19486660/185140578-d273c31e-0412-40c8-80da-27a6c193c5c1.png">

In #1387, I argue that this can be considered different from case of repeated repeat marks.

**Feature summary**

As @mscuthbert says in #1387, the 

> the parser shouldn't be going through and deciding exactly what you want to and don't want to copy

So, without using the parser itself, rectify this instead rather with a post hoc, final 'remove all time signature duplicates' check.

I.e., if this time signature is the same as foregoing context, then remove.

Come to this of it, this could be useful functionality to offer more centrally, e.g., on `stream.Stream` and optionally called in rntxt as one kind of use case.

**Intent**
[X] I plan on implementing this myself.

**Comment by mscuthbert** [comment]
I agree that this is different because there is no "4/4" token in the line beginning "m1" -- though I wonder if there's an easier solution such as appending default/header signature tokens later in the parse cycle or marking default/header tokens as something not to be copied.

What you propose could be a useful tool, but please don't put it on `stream.Stream` -- the module and the class are getting too big as it is (this is why makeNotation was factored out).  If it's just timeSignatures it should go in meter.tools.  If it's all signatures (key and clef could also be helpful), then either analysis/ or a new stream.tools file would be appropriate.

**Comment by MarkGotham** [comment]
Ok great.

I'll do something for all such cases (ts, ks, clef) in a new `stream.tools` and default to calling that from RNTXT.

Let's leave in a user option to not do so as there are some legitimate reasons to explicitly repeat time signatures etc.
