### ISSUE TITLE
Humdrum metadata not appearing as music21 metadata

### ISSUE THREAD

**Issue by mscuthbert** [cuthbertLab/music21#14]
Reported by craigsapp, Apr 2, 2013
What steps will reproduce the problem?

``` python
from music21 import *
jos0303e = converter.parse('http://jrp.ccarh.org/cgi-bin/jrp?a=humdrum&f=Jos0303e', format='humdrum')
jos0303e.show()
```

What is the expected output? What do you see instead?

I expect to see the title of a work when it is exported via MusicXML into Finale.  Instead, I see Music21 Fragment" as the title.  Also I expect to see the composer's name on the right-hand side of the first system, but I instead see "Music21".

What version of the product are you using? On what operating system?

Using OS X 10.8.3; Python 2.7.2; Music21 v. 1.5.0; Finale 2012c.r13

Please provide any additional information below.

It would be useful to display the composer and title of a work when displayed in Finale via MusicXML output from Music21.   Currently the title is set to "Music21 Fragment" and the composer is set to "Music21".  See the attached PNG image for the visual display of the example work Jos0303e.krn.

More preferable would be to preserve the title and composer information within the converted data structure, and this information would be inserted into the appropriate location in the MusicXML file being sent to Finale for display.  The MusicXML output from Music21 has this sort of title:

<movement-title>Music21 Fragment</movement-title>

In the Humdrum file, the title has this form:
   !!!OTL: Title goes here
Where the line starts with !!!OTL: and is followed by the text for the title (no linebreaks).  The title can be displayed in multiple languages.  In that case choose the first OTL entry in the file as the title to display.  For example in this Bach chorale:

http://kern.humdrum.org/data?l=371chorales&f=chor001.krn

There are two titles:

!!!OTL@@DE: Aus meines Herzens Grunde
!!!OTL@EN:      From the Depths of My Heart

The one which should be displayed is "Aus meines Herzens Grunde" since it is first.  It is also the in the primary language due to the two @ signs, but this should not be the reason to choose it as the title.

Also, I use HTML entity encoding for accented characters in Humdrum reference records, so it would be useful to parse these to get the correct accented characters.  For example the work:

http://kern.ccarh.org/ksdata?l=371chorales&file=chor172.krn

Has the title reference record:
   !!!OTL@@DE:  Sei gegr&uuml;&szlig;et, Jesu g&uuml;tig
which should be rendered as:
    Sei gegrüßet, Jesu gütig

Another consideration is that there are two levels of title information in Humdrum:

```
!!!OPR: title of the parent work
!!!OTL: title of the work
```

Just displaying the OTL entry is fine, but maybe a more advanced system would display two lines for the title.  When both OPR and OTL are present in the data, then display OPR on a line followed by OTL underneath it.

Currently the composer field in the MusicXML export from Music21 is:

```
 <identification>
    <creator type="composer">Music21</creator>
  </identification>
```

For the composer in Humdrum files, there is a reference record in this form:
    !!!COM: composer's name
If there is a comma in the composer's name, then the display of the name should be flipped at that comma.  For example:
    !!!COM: Bach, Johann Sebastian
should be displayed as
     Johann Sebastian Bach
or for a more parsimonious display, perhaps:
     J.S. Bach

There is also an attributed composer:
   !!!COA: An attributed composer's name
This should be used if there is no !!!COM: reference record.  If there are both COM and COA entries, then display only the first one.  There may be two or more COM/COA entries:
    !!!COM1: Composer one's name
    !!!COM2: composer two's name
In this case the !!!COM1: composer should be displayed.

For even fancier display, the catalog or opus number of a work could be displayed underneath the composer's name.  For example Bach BWV numbers can be extracted from the !!!SCT: reference record:

!!!COM: Bach, Johann Sebastian
!!!SCT: BWV 410

Which would be displayed on the right side of the first system as:
    J.S. Bach
    BWV 410

(I don't know if this can be done in MusicXML/Finale without much hacking -- perhaps by putting a newline in the composer entry).

If there is no scholarly catalog number in an !!!SCT: reference record, then it would be useful of the Opus were displayed underneath the composer.  The opus number is stored in an !!!OPS: record, while the sub-opus number is stored in !!!ONM:

For example:
   !!!OPS: op. 59
   !!!ONM: no. 3
would be displayed underneath the composer as 
    op. 59, no. 3
If the OPS or ONM contains only a number with no text for "op." or "no.", then it would be useful to add it.

I have not tested the following yet, but the copyright notice at the bottom of the page in Finale display should display the contents of a !!!YEC: reference record in the Humdrum file if it is present in the original data.
![screen shot 2013-04-02 at 7 37 27 pm](https://f.cloud.github.com/assets/3521479/1515269/c6eee170-4aff-11e3-835f-ded3b6519237.png)

**Comment by mscuthbert** [comment]
Priority is higher for title, composer, lower for other information that m21 can handle (except for date uncertainty, etc. which would be a good test of the m21 metadata system that goes beyond MusicXML), and lowest for things that m21 can't currently handle, such as language-specific titles, etc.

**Comment by johnMamish** [comment]
It looks to me like the problems could originate with [HumdrumDataCollection.InsertGlobalEvents()](https://github.com/cuthbertLab/music21/blob/master/music21/humdrum/spineParser.py#L662).  I see two issues with this function:

1. It is called twice.  The first time, it is called before self.eventList has anything in it.  Because self.eventList is empty, insertGlobalEvents can't do anything.

2. While the GlobalEvents may be correctly parsed, they are not correctly inserted into a metadata object by the insertGlobalEvents function.  The problem appears to be at [line 709](https://github.com/cuthbertLab/music21/blob/master/music21/humdrum/spineParser.py#L709) of spineParser.py.  The correctly parsed GlobalEvents are not put into a metadata object, they are just shoved into the top level of the score.

I made some quick and gross hacks to fix the above two problems.  With this code, only the title of the humdrum piece is properly read into the metadata, not composer or any other info.  These hacks can be found in my forked copy of music21.  I just added about 5 lines to insertGlobalEvents().  [here is the fix for bullet point 1](https://github.com/johnMamish/music21/blob/master/music21/humdrum/spineParser.py#L674) [here is the fix for bullet point 2](https://github.com/johnMamish/music21/blob/master/music21/humdrum/spineParser.py#L716)

Once you can confirm with me that I'm taking the right approach, I will follow up and add the other info to the metadata.

(apologies for the messed up whitespace in my commit... my emacs is not configured right.  If you decide to merge in my changes, I will fix the whitespace.)

**Comment by mscuthbert** [comment]
these look like a great approach to the problem.  Thank you!  Please make a fresh branch off of the master git repository with just these changes and let's start pull request merging.  :-)  Thanks!

**Comment by johnMamish** [comment]
Alright, I have a pull request pending from my own fork

I gotta say, your CI system is pretty cool.  I didn't know that could be integrated so smoothly with github.

**Comment by mscuthbert** [comment]
Hi John! I used your method to get most metadata parsing working from humdrum to music21.   I used a slightly different approach, but I'm glad for your code ideas.   It's in the commit for today.

Dates are still missing, but now it's easy to add new data.  It's all in the GlobalReference object.

Thanks!
