### ISSUE TITLE
Start and end notes under `Ottava` spanner exported incorrectly due to `toWrittenPitch()`

### ISSUE THREAD

**Issue by NeroBlackstone** [cuthbertLab/music21#1419]
**music21 version**

`7.3.3`   

**Problem summary**

Pitch of some notes incorrect after .musicxml file parsed by  music21.

**Steps to reproduce**

```
from music21 import *
s=converter.parse('1.musicxml')
s.show()
```

**Expected vs. actual behavior**

Original file:
![original xml](https://user-images.githubusercontent.com/17470335/189474510-0684b8ed-b0d8-4852-b0eb-5c19d07b0fa0.png)

After parse:
![after parse](https://user-images.githubusercontent.com/17470335/189474519-8fcacfa2-0342-4a17-b9d2-2df612387c9b.png)

So C5 is incorrectly parsed as C4.

**More information**

musicxml file:
[1.zip](https://github.com/cuthbertLab/music21/files/9539801/1.zip)

OS: linux-lts 5.15.64-1

**Comment by mscuthbert** [comment]
Hi Nero -- what does the MusicXML file output from MuseScore look like in m1 (beginning) and m8 (end)?  There are four possible problems:

1) MuseScore is not outputting MusicXML the way you intend the piece to be interpreted (either user error or MuseScore error; not music21).
2) Music21 is not reading the MusicXML properly (music21 problem -- we would fix); the Stream is incorrect.
3) Music21 is not outputting the MusicXML properly (music21 problem -- we would fix)
4) MuseScore is not reading properly formatted MusicXML properly (MuseScore error; not music21)

Can you isolate what is happening w/ the MusicXML specs and determine which of these 4 errors is happening here?  Otherwise, if you need someone to do this for you you may need to look into paid consulting support.

**Comment by NeroBlackstone** [comment]
Thank you, mscuthbert.

I have read .musicxml file before and after music21 parser.
And I think it's possible music21 bug:

For your question 1, I think muse score generate correct .musicxml file.
For example in measure 1: (Original pitch in .mscz is **B-5 F5 E-6 F6**)
After musescore .musicxml export:

``` xml
<measure number="1" width="207.21">
...
<pitch>
          <step>B</step>
          <alter>-1</alter>
          <octave>5</octave>
</pitch>
....
<pitch>
          <step>F</step>
          <octave>5</octave>
</pitch>
...
<pitch>
          <step>E</step>
          <alter>-1</alter>
          <octave>6</octave>
</pitch>
...
<pitch>
          <step>F</step>
          <octave>6</octave>
</pitch>
</measure>
```

It's good, right? So it's not muscscore bug.

For question 2:
Execute:
``` python
from music21 import *

s = converter.parse('1.musicxml')
piano_rh = s.parts[0]
print(piano_rh.measure(1).pitches)
s.show()

s.write(fp=r'out.musicxml')
```

Console output is:
```
[<music21.pitch.Pitch B-2>, 
<music21.pitch.Pitch D3>,
 <music21.pitch.Pitch F3>, 
<music21.pitch.Pitch B-5>,
 <music21.pitch.Pitch F5>, 
<music21.pitch.Pitch E-6>, 
<music21.pitch.Pitch F6>]
```

I don't know the first three note come from where.

For question 3:
`out.musicxml` is:
``` xml
<measure number="1" width="207.21">
...
<pitch>
          <step>B</step>
          <alter>-1</alter>
          <octave>4</octave> <!-- WHAT'S WRONG ,should be 5-->
</pitch>
...
<pitch>
          <step>F</step>
          <octave>5</octave>
</pitch>
...
<pitch>
          <step>E</step>
          <alter>-1</alter>
          <octave>6</octave>
</pitch>
...
<pitch>
          <step>F</step>
          <octave>6</octave>
</pitch>
...
</measure>
```

So I think it's music21 bug.

My python version is 3.10

**Comment by jacobtylerwalls** [comment]
`toWrittenPitch()`, usually needed for musicxml display, calls `Ottava.undoTransposition(), which isn't--since musicXML encodes pitches under ottavas at sounding pitch (or in music21's terms, as "non-transposing spanners").

So `toWrittenPitch` should probably take an argument `transposeSpanners=True` so that the musicxml exporter can call it with the value False.

This is only affecting the first and last notes of the spanner because `undoTransposition()` ignores the intermediary elements of the spanner, see #249.

**Comment by NeroBlackstone** [comment]
Any other alternatives to music21 to recommend?
I'm sorry for post something unrelated to this bug, but I have an experiment to do.🥲
Thank you very much!q

**Comment by jacobtylerwalls** [comment]
As a workaround, you can set the attribute `atSoundingPitch` to False on each `Part` object (or `PartStaff`, in your case, a subclass of `Part`):
```python
from music21 import *
myScore = converter.parse('../Downloads/1.musicxml')
for p in myScore.parts:
    p.atSoundingPitch = False
myScore.show()
```
This will work here since you don't have transposing instruments such as clarinets or trumpets.

**Comment by mscuthbert** [comment]
Definitely the bug in not processing intermediate notes in a spanner is something that I want to fix.  It should not be too hard to do if someone wants to take it on.  The Q is what types of elements are included in the intermediary sections?  Presumably not rests or clefs, etc. but definitely notes and chords but not unpitched and we can't determine what is likely to be in there based on first and last elements alone.

**Comment by mscuthbert** [comment]
Okay -- I think I got an answer to "What to include" -- (1) we add to spanner.Spanner (the base object) a set of what objects to include in autoAdd (.autoAddClasses).  If defined, we add only those classes during autoadd.  I think that Ottava and Slur can be defined to have {GeneralNote} as their set (since they will transpose .pitches and Rests have empty .pitches, they're okay to include.  StaffGroups will have Part set in their autoAddClasses.  

(2) If undefined and there are no elements then it's treated as Music21Object.  If undefined and there is one element, use that class.  If undefined and there are two elements, then eventually use the intersection of their MRO.

It still doesn't solve the problem of knowing when to end IF the two elements are in different hierarchies.  It probably needs to do something like this https://leetcode.com/problems/lowest-common-ancestor-of-a-binary-tree/  (They're not binary trees, but given that there are only two objects, it works out to be the same problem.

**Comment by jacobtylerwalls** [comment]
After responding to @gregchapman-dev at https://github.com/gregchapman-dev/converter21/issues/8#issuecomment-1325653063, I now think we need `ottavasToSounding=True` to handle the option to convert either transposing or non-transposing spanners to _Sounding_ pitch as musicxml requires, despite everything else being converted to written pitch. Musicxml documents expect sounding pitch w/r/t transposition and written pitch w/r/t ottavas.

**Comment by mscuthbert** [comment]
yes.  agreed.

**Comment by gregchapman-dev** [comment]
I will work up a PR for this. (Please assign to me.)

It sounds like there are a few bits to this:
1. Add ottavasToSounding=True option to stream.toWrittenPitch.
2. Call stream.toWrittenPitch with that parameter in m21ToXml.py (and maybe in other writers, including my Humdrum writer).
3. Figure out a way to allow processing every element that is intended by the spanner, even if the spanner only includes start and end element.  (I have some questions about the intended approach here... should we actually add the intermediate notes to the spanner at some point?  Or have an iterator that iterates over all the elements that _should_ be in the spanner?)
5. Figure out a way to successfully process a spanner that starts and ends in different sub-hierarchies of the score.  This is perhaps separable into another PR, but as long as I'm in here, I think this PR would benefit from it.
6. Maybe factor out a separate routine that would help apps like musicdiff compare a transposing Ottava's notes with a non-transposing Ottava's notes (perhaps just a routine that returns all the sounding-pitch notes from an Ottava).

**Comment by gregchapman-dev** [comment]
Oh, and I am going to start the PR from my SpannerAnchor PR branch, since MEI <octave> elements often end with a timestamp instead of a note/chord.  I might even find some SpannerAnchor bugs.

**Comment by gregchapman-dev** [comment]
First question (@jacobtylerwalls @mscuthbert): Ottava.perform/undoTransposition don't really work as is.  First, they can't really do the job without access to the elements that _should_ be in the spanner, and second, they change the visibility of the Ottava, which seems like a really wrong thing to do during write().  I'm thinking I should deprecate Ottava.perform/undoTransposition, move those routines to stream/base.py, and pass them the highest-level stream (most likely a Part or PartStaff) in which to look recursively for notes/chords to consider part of the Ottava.  Alternatively, I could fix the routines in place in Ottava, but add a stream.Stream parameter (it could default to None, I guess, for backward-compatible behavior: no search for other elements).  Do you have a preference?

**Comment by jacobtylerwalls** [comment]
A recursive search for notes contained between spanner termini sounds useful for more than just ottavas, which would be my argument for not deprecating the undo/performTransposition API. See @mscuthbert's brainstorm for that at #249.

> they change the visibility of the Ottava

I didn't know it was doing this. Is it setting hideObjectOnPrint? I'd be ok with documenting a behavior change (to no longer change visibility).

**Comment by gregchapman-dev** [comment]
Yes, they set hideObjectOnPrint to hide the "soundingPitch" version of the Ottava.  Very weird.

Reading the brainstorm now.

**Comment by gregchapman-dev** [comment]
Ah!  "Fill when importing MusicXML" sounds awesome.  I was assuming the exporters would have to deal with non-filled spanners.  A utility routine that fills an offset-spanning spanner sounds very useful (I'm on it; I can see that tempo.interpolateElements() has some of the logic I will need).  And I'll do a quick survey of the various parsers (including my two) to see who might be needing to make this call.

**Comment by gregchapman-dev** [comment]
Ah, filling of "vertical" spanners (e.g. ArpeggioMarkSpanner) might be interesting, too.

**Comment by mscuthbert** [comment]
yes -- I've been wanting a way to fill spanners with intermediary elements and to record whether a spanner contains just end-elements, all-elements, or unknown.  I'm sure I've put my notes on this in some issue recently.

I'm not sure I'll be able to do much major music21 work until the Xmas holidays, I'm afraid.  There's just too much else on my plate.

**Comment by gregchapman-dev** [comment]
I will work on the filling of spanners over in #1486, since it's needed for Ottavas.  Current plan (these never hold up, but I'm writing it down anyway):
1. Add new data member to class Spanner to track whether a Spanner contains just end-elements, all-elements, or unknown.
2. Add new routine to class Spanner that fills in the intermediate <objects of class that is appropriate for this particular Spanner>, given a stream to search recursively in.  Hmmm... might need to stash that stream off in the Spanner?
3. "Vertical" spanners (e.g. ArpeggioMarkSpanner) will need to be filled differently, so will probably need to override the base implementation of the "fill" routine.

**Comment by gregchapman-dev** [comment]
> Okay -- I think I got an answer to "What to include" -- (1) we add to spanner.Spanner (the base object) a set of what objects to include in autoAdd (.autoAddClasses). If defined, we add only those classes during autoadd. I think that Ottava and Slur can be defined to have {GeneralNote} as their set (since they will transpose .pitches and Rests have empty .pitches, they're okay to include. StaffGroups will have Part set in their autoAddClasses.

I'm doing this right now, and I'm running into circular imports.  I can't import note (to put note.GeneralNote in the autoAddClasses) or stream (to recurse a stream looking for elements in the right offset range) in spanner.py, or things crash (with partial Spanner definition, "likely a circular import").  

@mscuthbert and @jacobtylerwalls, any thoughts about how to manage this?  I can move the `fillIntermediateElements` routine into stream/base.py, which helps, but I still need spanner.py to be able to talk about element classes.  Maybe by name (str) instead of by class?  What do you think?

**Comment by gregchapman-dev** [comment]
I have a fairly gross workaround in place over in the PR # 1486.  Take a look.

**Comment by jacobtylerwalls** [comment]
#1486 fixes the original report. If there are additional todos left over from that work, please feel free to start a new thread. Thanks, all!
