### ISSUE TITLE
Building the documentation fails

### ISSUE THREAD

**Issue by raphaelfournier** [cuthbertLab/music21#146]
I have tried the instructions given on [this page](http://web.mit.edu/music21/doc/developerReference/buildingDocumentation.html), on two different machines (Ubuntu 14.04 on one and Archlinux on the other), but each time I run `python make.py` leads to an error such as the following: 

	Traceback (most recent call last):
	  File "music21/documentation/make.py", line 195, in <module>
	    db.run()
	  File "music21/documentation/make.py", line 50, in run
	    self.runBuild()
	  File "music21/documentation/make.py", line 70, in runBuild
	    documentation.writers.IPythonNotebookReSTWriter().run()
	  File "/usr/lib/python3.5/site-packages/music21/documentation/writers.py", line 243, in run
	    self.writeIndexRst()
	  File "/usr/lib/python3.5/site-packages/music21/documentation/writers.py", line 262, in writeIndexRst
	    ipfp[0])
	IndexError: list index out of range

My ipython installations whole systems are up-to-date (Python version differ, on one computer it's 3.5, on the other it's 2.7). This happens whichever the argument for make.py are ("html", "latex", or none to try a default behavior). I also tried with and without `sudo` rights.

Does anyone have any idea how to obtain a working script?

**Comment by mscuthbert** [comment]
The problem here is arising because there are no iPythonNotebook files properly converted.  If you are sure that you have pandoc, and sphinx, and nbconvert installed?  If you are sure on all those but you don't have iPython/Jupyter installed, try installing that too.

If that fails, I'm afraid you'll need to debug it on your own or purchase support time.  Because of the number of different architectures, we don't offer any free support for systems other than Windows 7+ or Mac OS X (Yosemite+).
