### ISSUE TITLE
Key in Stream leads to misproduced MIDI

### ISSUE THREAD

**Issue by garncarz** [cuthbertLab/music21#149]
[This commit](https://github.com/garncarz/songs/commit/0a3e481feb260a31db6fff37ec5b015d8cb45307), which just adds keys to stream.Parts, and works fine with `.show()` and MuseScore, produces broken MIDI (`.show('midi')` with TiMidity++). Synchronization problems begin in the second half.

```
In [73]: po.s.show('midi')
Playing /tmp/music21/tmp8toe5s6g.mid
MIDI file: /tmp/music21/tmp8toe5s6g.mid
Format: 1  Tracks: 3  Divisions: 1024
Sequence:
Invalid key signature
Invalid key signature
Invalid key signature
Invalid key signature
Invalid key signature
Track name:
Invalid key signature
Invalid key signature
Invalid key signature
Invalid key signature
Invalid key signature
Track name: Violin
Invalid key signature
Invalid key signature
Invalid key signature
Invalid key signature
Invalid key signature
Invalid key signature
Invalid key signature
```

**Comment by mscuthbert** [comment]
Hi -- I'm going to need you to restate the specific music21 problem happening here.  My reading of the problem is "a commit in a different software package causes a bug in a midi player I've never heard of."  What are the particular music21 steps needed to cause the problem and what is the bug in the MIDI output of music21 (why couldn't the bug be in TiMidity instead?)  THnaks!

**Comment by garncarz** [comment]
Hi, thanks for reply. It's not actually a different software package, just a Python file constructing a song. And the thing is the produced MIDI file was alright before this commit. The commit just adds keys to the stream's parts, like this:

```py
chords = stream.Part(id='chords')
chords.append(key.Key('F'))
```
 
Then notes in the produced MIDI file starts to be out of sync (in the second half). I tried importing the MIDI file even in MuseScore and the problems begin at bar 76. (But those keys are inserted into the stream throughout the whole song, from the beginning.)

So it seems there's a bug in writing `key.Key` in the MIDI format, it would better be ignored there.

I believe TiMidity is quite a standard MIDI player in Linux, what is your favourite one?

**Comment by mscuthbert** [comment]
Hi Ondrej -- I know to you it's just another python file, but from my side, figuring out what it is doing so I can know if it's a music21 error or a "songs" error or a TiMidity error will take me a lot of time.  What I need to see is a minimum set of music21 code that causes incorrect MIDI to be written out and to show what is wrong with the midi.  Otherwise the bug is going to stay open until someone interested in TiMidity in particular fixes it.

**Comment by garncarz** [comment]
Hello Michael, sorry for the delay. I'm able to reproduce the "Invalid key signature" error with this code:

```py
from music21 import *

s = stream.Stream()

s.append([
    key.Key('F'),
    note.Note('f4'),
    note.Note('a4'),
    note.Note('c5'),
    note.Note('f5'),

    key.Key('C'),
    note.Note('c4'),
    note.Note('e4'),
    note.Note('g4'),
    note.Note('c5'),

    key.Key('A'),
    note.Note('a4'),
    note.Note('cis5'),
    note.Note('e5'),
    note.Note('a5'),
])

s.show('midi')
```

TiMidity's output is then:

```
Playing /tmp/music21/tmpnrwn7jgo.mid
MIDI file: /tmp/music21/tmpnrwn7jgo.mid
Format: 1  Tracks: 1  Divisions: 1024
Sequence:
Invalid key signature
Playing time: ~10 seconds
Notes cut: 0
Notes lost totally: 0
```

But all notes are timed as they should be, the example is too simple to capture the synchronization error.

I'm attaching a MIDI file produced by Music21: [tmprg7m3n_g.zip](https://github.com/cuthbertLab/music21/files/201664/tmprg7m3n_g.zip) (I had to zip it to be able to upload it here) which when imported into MuseScore shows the synchronization error starting in bar 76. (The source for it is the originally mentioned commit.) (When directly generating MusicXML, it's all fine.)

If I can provide some more information, please ask.

**Comment by garncarz** [comment]
Maybe I could restate the problem like this:

[This code](https://github.com/garncarz/songs/blob/0a3e481feb260a31db6fff37ec5b015d8cb45307/po.py) using Music21 version 2.2.1 produces [this MIDI & this MusicXML files](https://github.com/cuthbertLab/music21/files/201676/po.zip).

The XML file imported into MuseScore (version 2.0.1) is alright, but the MIDI isn't, the key signatures aren't set and synchronization between staffs breaks from bar 76. (And the same error can be seen/heard when using the TiMidity MIDI player.)

**Comment by garncarz** [comment]
Maybe it's related to this:

```py
>>> k
<music21.key.Key of F major>

>>> midi.translate.keySignatureToMidiEvents(k)
[<MidiEvent DeltaTime, t=0, track=None, channel=None>,
 <MidiEvent KEY_SIGNATURE, t=None, track=None, channel=1, data='ÿ\x00'>]
```

But according to [the code](https://github.com/cuthbertLab/music21/blob/master/music21/midi/translate.py#L874) the data should be more like `\\x02\\x00` (backslashes doubled).

(I'm using Python 3.4.3.)

**Comment by mscuthbert** [comment]
Thanks. Now THIS was something that I could fix -- and gave the important piece of information (Py 3) that led to a fix.  

MIDI is the only often-used fully binary format that music21 supports.  The distinction between bytes and strings in Python3 can lead to some difficult bugs if binary data (such as KEY_SIGNATURE) is encoded as string data.  When the first Python3 compatible version of music21 was released, I didn't really know what I was doing with regard to string/binary data -- when everything passed, then i thought it worked.  Looking back now, being pointed in the right direction, the bug was so obvious to me -- I believe it's fixed completely.  And it's in the latest github.  When the CI tests pass it should be ready to go (about 30 minutes)

**Comment by mscuthbert** [comment]
All passing now.

**Comment by garncarz** [comment]
Thanks! :+1: It works well now.
