### ISSUE TITLE
Trailing rests created that don't agree with the quantization scheme

### ISSUE THREAD

**Issue by smirkingman** [cuthbertLab/music21#1536]
**music21 version**

`8.1.0`   

**Problem summary**
I want to flatten a score for reading by another program which needs a single track.
When I read a score with converter.parse, flatten it and re-write it with score.write, the notes' timings are wonky (it sounds wrong).
Using other quarterLengthDivisors doesn't change the results.
This happens on many, but not all files.
What is the correct way to do this please?

**Steps to reproduce**

```
from music21 import *
import subprocess
import os

def makexml(source, target):
    # Convert a midi to MusicXML with MuseScore
    musescore_path = r'C:\Program Files\MuseScore 3\bin\MuseScore3.exe'
    cmd_str = f'"{musescore_path}" "{source}" -o "{target}" -w'
    subprocess.run(cmd_str)

piece = 'mazurka'  # or 'rondo'
# Convert with MuseScore, as recommended here
# https://github.com/cuthbertLab/music21/issues/1530#issuecomment-1440759880
xml_path = 'temp.mxl'
makexml(piece + '.mid', xml_path)
# Changing from default quarterLengthDivisors=((4, 3)) to quarterLengthDivisors=((8, 6))
# makes no difference, output still wonky
score = converter.parse(xml_path)
os.remove(xml_path)
score = score.flatten()  # Flattened or not, still wonky
score.write(fmt='midi', fp=piece + '.flat.mid')
```

**Expected vs. actual behavior**
See attached mazurka and rondo files.
[samples.zip](https://github.com/cuthbertLab/music21/files/10981106/samples.zip)

**Comment by mscuthbert** [comment]
You shouldn't flatten() the score.  Use chordify() instead.

**Comment by smirkingman** [comment]
chordify() sounds even worse.

Even this, with no processing,:
```
score = converter.parse(xml_path)
score.write(fmt='midi', fp=piece + '.flat.mid')
```
produces output that sounds very different to the input - listen to the samples -
and setting quarterLengthDivisors=(X, Y) for all X in (2,4,8,12,16,32) and Y in (3,9,12,18,27) doesn't help.

**Comment by smirkingman** [comment]
### Steps to reproduce
with [input] = 'mazurka' and 'rondo':

```
score = converter.parse('[input].mid')
score.write(fmt='midi', fp=[input] + '.flat.mid')
```

The outputs will be mazurka.**FLAT**.mid and rondo.**FLAT**.mid.

### Expected behaviour:
The outputs sound identical to the inputs.

### Actual behaviour:
Listening to the first few bars of the two outputs, it is obvious that the note timings are incorrect.

**Comment by jacobtylerwalls** [comment]
Thanks for the additional details.

> Expected behaviour:
The outputs sound identical to the inputs.

If this is what is desired, then you should use `quantizePost=False` to turn off quantizing. Otherwise the outputs will definitely be different. This is how different a result you get from importing the Rondo source into MuseScore:

![musescore-quantization](https://user-images.githubusercontent.com/38668450/226141008-d31c87ec-09c5-4283-8595-b0c07841851b.png)

Listening to the source, it's not played in a strict enough tempo for a naive quantization algorithm to produce something close enough to the original. (That said, maybe another program could do a "better" job here, by introducing assumptions music21 doesn't claim to make.)

***

quantizePost=False holds up pretty well: here is the source layered against the parsed music21 stream (with quantizePost=False) and reexported to MIDI (and displayed in a program that doesn't quantize, like GarageBand). Notice only extremely trivial time discrepancies:
![layered](https://user-images.githubusercontent.com/38668450/226141113-337f5c44-cc9f-47c6-91b3-86cf0d0f20b3.jpeg)

***

> Are the divisors allowed to multiply? Does (4, 3) allow 1/12th? I can't remember

That's a good question. I think the spirit of #811 was that we could try to avoid creating these gaps. So I'm willing to leave this open for a little investigation. (In fact, right now I'm about to look into why #811 didn't cover this after all...)

***

> Actual behaviour:
Listening to the first few bars of the two outputs, it is obvious that the note timings are incorrect.

This wasn't obvious to me--quantization is happening as promised. If there's something more specific you're unsure about, you could annotate the output of a specific measure like I did [here](https://github.com/cuthbertLab/music21/issues/1536#issuecomment-1472912753).

**Comment by jacobtylerwalls** [comment]
I see now why #811 didn't handle this. There's an interaction between the #811 feature and the #641 feature just below it.

This is a start, but it needs to run recursively. I'll get around to a fix at some point.

```diff
diff --git a/music21/stream/base.py b/music21/stream/base.py
index e10404e09..a0e72156e 100644
--- a/music21/stream/base.py
+++ b/music21/stream/base.py
@@ -9328,6 +9328,8 @@ class Stream(core.StreamCore, t.Generic[M21ObjType]):
         if recurse is True:
             useStreams = list(returnStream.recurse(streamsOnly=True, includeSelf=True))
 
+        smallest_tolerable_gap = 1 / max(quarterLengthDivisors)
+
         rests_lacking_durations: list[note.Rest] = []
         for useStream in useStreams:
             for i, e in enumerate(useStream._elements):
@@ -9355,10 +9357,17 @@ class Stream(core.StreamCore, t.Generic[M21ObjType]):
                         look_ahead_result = bestMatch(float(next_offset), quarterLengthDivisors)
                         next_offset = look_ahead_result.match
                         next_divisor = look_ahead_result.divisor
-                        if (0 < next_offset - (e.offset + d_matchTuple.match)
-                                < 1 / max(quarterLengthDivisors)):
+                        if d_matchTuple.match > 0:
+                            this_el_end_time = opFrac(e.offset + d_matchTuple.match)
+                        else:
+                            # Zero! Anticipate the nonzero duration that would be created below.
+                            this_el_end_time = opFrac(e.offset + smallest_tolerable_gap)
+                        if (0 < (next_offset - this_el_end_time) < smallest_tolerable_gap):
                             # Overwrite the earlier matchTuple with a better result
                             d_matchTuple = bestMatch(float(ql), (next_divisor,))
+                            if d_matchTuple.match == 0:
+                                # recalculate this_el_end_time and do this again ...
+                                d_matchTuple = bestMatch(smallest_tolerable_gap, (next_divisor,))
                     # Enforce nonzero duration for non-grace notes
                     if (d_matchTuple.match == 0
                             and isinstance(e, note.NotRest)
```
