### ISSUE TITLE
Print out the pedal information in a musicxml file using music21

### ISSUE THREAD

**Issue by yedaming12** [cuthbertLab/music21#1552]
How can I print out the pedal information in a musicxml file using music21? I found that the pedal information is stored under the direction element, but I tried many methods and none of them could print it out.

**Comment by jacobtylerwalls** [comment]
Questions like these are best suited for the mailing list, rather than here, which is for bug reports. There is a gentle introduction to searching streams and retrieving information [here](https://groups.google.com/g/music21list/c/4zjsrZXkc2w/m/TjeTy1N1AQAJ), otherwise the [user's guide](https://web.mit.edu/music21/doc/) is your best bet.

**Comment by yedaming12** [comment]
Sorry, I don't know what elements the music21 library parses pedal information into, and I can't find any description of pedal information in the music21‘s official documentation.

**Comment by yedaming12** [comment]
> Questions like these are best suited for the mailing list, rather than here, which is for bug reports. There is a gentle introduction to searching streams and retrieving information [here](https://groups.google.com/g/music21list/c/4zjsrZXkc2w/m/TjeTy1N1AQAJ), otherwise the [user's guide](https://web.mit.edu/music21/doc/) is your best bet.

Sorry, I don't know what elements the music21 library parses pedal information into, and I can't find any description of pedal information in the music21‘s official documentation.
