### ISSUE TITLE
Music21Object.id problem

### ISSUE THREAD

**Issue by twcook** [cuthbertLab/music21#175]
The id of all objects is settable, and this is great.  However, there are 538 places in the code where the id(object)  is used (object could be anything such as c, a, ...)  so this circumvents using the assigned ID.  

My initial discovery is due the fact that I assigned IDs when building up a score using loops and function calls, then in stream/core.py _addElementPreProcess id(element) is tested instead of element.id when writing to MusicXML or MIDI.

Python object ids are not guaranteed to be unique  during the life of the program so they should not be persistent across function calls.  

I suggest this initial fix:

in music21/base.py:
    `
     from uuid import uuid4
`
then at line 396 (or so):

```
        if "id" in keywords:
            self.id = keywords["id"]
        else:
            self.id = 'm21-'+str(uuid4())

```
This produces a unique id that can be persisted and used as needed. 

In stream/core.py line 280, replace

            idElement = id(element)

with

            idElement = element.id

also in the exception change id(element) to element.id 

I am sure that there are other issues like this lurking because of the id(object) checks.  But I haven't seen them yet. 

Thanks.

**Comment by twcook** [comment]
If you want these changes, I will fork the project and create a branch to correct this issue. 
Change all instances of using id(object) to object.id. ???

**Comment by mscuthbert** [comment]
Hi Tim -- you've noticed that the use of ids is a mess -- there are times where we are using id(x) because we want the current memory address and times where we want to use the id set upon creation.  Any help in descrambling this would be a big help.

Unfortunately, the uuid4() solution won't work:
```
In [2]: %timeit uuid.uuid4()
100000 loops, best of 3: 9.82 µs per loop

In [3]: %timeit base.Music21Object()
100000 loops, best of 3: 5.5 µs per loop
```
I looked into this before -- adding UUID would triple the creation time of general Music21Objects -- add 50% to the time to create streams or rests, and even add 20% to the creation time of the more complex Note object.  If Python would adopt a c-based UUID system then it'd be something to consider closely though.

**Comment by twcook** [comment]
Hmmm, do you say it won't work because of the live streaming capability?  I admit my interest has only been in creating (atonal) music and writing or XML or MIDI files.  I haven't tested any streaming.

There are some C based UUID libs.  Maybe I'll test some of those and then wrap one.

**Comment by mscuthbert** [comment]
by Stream I mean the music21.stream.Stream class, etc.

We don't have any custom C libraries in music21 because then we'd have to test building on lots of different systems and provide binary builds for Windows, etc., so if we went UUID it'd have to be through the pure-python method.  I did a preliminary test and it looks like it'd add about 25% to the overall music21 runtime, so I don't see the advantages as worth it.

Can you submit code that does not work in the current system that would work with some changes of id(x) to x.id?  Thanks!  The stream.core call to id(x) seems to me like the right thing to do no matter what.

Best,
Myke

**Comment by twcook** [comment]
I have given you access to to a repo (https://github.com/DataInsightsInc/TwelveToneComposer) so that you can try the music21_based branch.  Because of the issue with the id checking the problem happens randomly.  Because there is no way to calculate when an object id will get reused. I am just learning to use Tkinter so there is a basic GUI but if you execute 'python ttc.py'  it will load the default config file.  Then just try to Generate a MusicXML file. It will eventually fail because of a duplicate id problem. 

So the id situation needs to be fixed.  The questions is best how to generate guaranteed unique ids and then use them everywhere instead of the object id.  Probably a function based on system time will be sufficient.

**Comment by twcook** [comment]
I did some profiling using the code below.  I think you'll find the results interesting. 


```
import music21 as m21
from uuid import uuid4
import cProfile, pstats, io
import time

def test_1():
    for x in range(0,10000):
        anote = m21.note.Note('C', id='d-'+str(uuid4()))

def test_2():
    for x in range(0,10000):
        anote = m21.note.Note('C')

def test_3():
    for x in range(0,10000):
        anote = m21.note.Note('C', id=str(time.time()))

if __name__ == "__main__":
    pr = cProfile.Profile()
    pr.enable()
    print('With UUID')
    test_1()
    pr.disable()
    s = io.StringIO()
    sortby = 'cumulative'
    ps = pstats.Stats(pr, stream=s).sort_stats(sortby)
    ps.print_stats()
    print(s.getvalue())

    pr.enable()
    print('With id(obj)')
    test_2()
    pr.disable()
    s = io.StringIO()
    sortby = 'cumulative'
    ps = pstats.Stats(pr, stream=s).sort_stats(sortby)
    ps.print_stats()
    print(s.getvalue())

    pr.enable()
    print('With time.time')
    test_2()
    pr.disable()
    s = io.StringIO()
    sortby = 'cumulative'
    ps = pstats.Stats(pr, stream=s).sort_stats(sortby)
    ps.print_stats()
    print(s.getvalue())

```

**Comment by twcook** [comment]
I used this profiling code to do some timing tests.  Across several runs there is little difference between using the id(obj) approach and using time.time 

```
import music21 as m21
from uuid import uuid4
import cProfile, pstats, io
import time

def test_1():
    for x in range(0,10000):
        anote = m21.note.Note('C', id='d-'+str(uuid4()))

def test_2():
    for x in range(0,10000):
        anote = m21.note.Note('C')

def test_3():
    for x in range(0,10000):
        anote = m21.note.Note('C', id=str(time.time()))

if __name__ == "__main__":

    sortby = 'cumulative'

    pr1 = cProfile.Profile()
    pr1.enable()
    print('With UUID')
    test_1()
    pr1.disable()
    s1 = io.StringIO()
    ps1 = pstats.Stats(pr1, stream=s1).sort_stats(sortby)
    ps1.print_stats()
    print(s1.getvalue())

    pr2 = cProfile.Profile()
    pr2.enable()
    print('With id(obj)')
    test_2()
    pr2.disable()
    s2 = io.StringIO()
    ps2 = pstats.Stats(pr2, stream=s2).sort_stats(sortby)
    ps2.print_stats()
    print(s2.getvalue())

    pr3 = cProfile.Profile()
    pr3.enable()
    print('With time.time')
    test_2()
    pr3.disable()
    s3 = io.StringIO()
    ps3 = pstats.Stats(pr3, stream=s3).sort_stats(sortby)
    ps3.print_stats()
    print(s3.getvalue())

```

**Comment by mscuthbert** [comment]
Repo is removed -- can't debug; Sorry!

**Comment by ahankinson** [comment]
Just out of interest and for future reference should this come up again, it looks like all the platforms use built-in C-based UUID generation.

https://github.com/python/cpython/blob/master/Lib/uuid.py#L462

**Comment by mscuthbert** [comment]
Unfortunately, if we've already gotten the C-based speedups, that means it's even less likely that we'll be able to go this route in the future.  My guess is that there's something in the use of ids beyond how music21 uses them that is causing the problems above -- I use the system pretty intensely and not had an id collision/reuse problems since the stream storage system of v.2 was implemented.  So I'd need to see minimal code that can cause the problem

**Comment by ahankinson** [comment]
I guess it would depend on whether two objects were allocated to the same memory space -- then they would have the same ID. It would also be a problem if you stored the ID as a string, and then deep-copied it to a new object. Then `note.id` and `id(note)` would not be the same. 

I wouldn't go down a `time` path either, since it is possible that two objects can be created at the same time in a parallel context (threading or otherwise). 

Looking at the code for `uuid.py` it doesn't look like it's super optimized, so it may be that it would be possible to implement faster uuid generation in Python. If one were to take that on, `python-libuuid` would probably be a good place to start.

https://github.com/dln/python-libuuid
