### ISSUE TITLE
Provide easy way to disable MIDI quantization

### ISSUE THREAD

**Issue by alexandermorgan** [cuthbertLab/music21#192]
In processing a string quartet, I get the same offset values for the C and Bb in measure 2, beat 3 of the first violin in the snapshot below. 
![image](https://cloud.githubusercontent.com/assets/2601689/18720886/ddc98484-7ffb-11e6-8705-3e5735bf399a.png)
I'm running into this problem in music21 3.1.0, but not in 2.1.2. The way I use music21 to determine the offset of a note is with the following logic where `event` has already been filtered to make sure it has a 'Note', 'Rest', or 'Chord' type:

```
for y in event.contextSites():
    if y[0] is part:
        return y[1]
```

When I make a pandas.Series of these note, rest, or chord objects with their offsets as determined by the code above as the index, these are the first few values for the first violin:

```
0.000000               <music21.note.Rest rest>
3.000000                  <music21.note.Note E>
4.000000                  <music21.note.Note F>
5.500000                  <music21.note.Note A>
6.000000                  <music21.note.Note C>
6.000000                 <music21.note.Note B->
6.333333               <music21.note.Rest rest>
6.500000                  <music21.note.Note A>
7.000000                 <music21.note.Note B->
7.500000                  <music21.note.Note D>
```

Should I be using contextSites() differently in 3.1.0, or is there something else I'm missing? Just let me know if you'd like me to send the file. Thanks.

**Comment by alexandermorgan** [comment]
In case it's important, the file I have for this piece is in midi.

**Comment by mscuthbert** [comment]
Yes, MIDI files are quantized because there are many performed MIDI files that would otherwise be a mess.  Either disable quantization in the MIDI or much better preprocess MIDI in Finale or something and export to XML.

**Comment by alexandermorgan** [comment]
Ok, so this is the new expected behavior, thank you. I looked through the documentation to find where quantize() gets called but I couldn't find it. If we import a midi file and then run .recurse() on its parts, where can I pass an argument to disable quantization? I couldn't find one in the .recurse() or .parseFile() docs arguments.
```
score = music21.converter.parseFile('piece_pathname.midi')
recursed_parts = [part.recurse() for part in score.parts]
```

**Comment by mscuthbert** [comment]
I've changed the name of the issue to reflect the next work to be done.  If you do a debugger through the system, I think you can see where the quantization happens and see a way to disable it, but it's not easily user exposed right now.  I don't think I'll be able to get to this during this term though however.

**Comment by alexandermorgan** [comment]
@mscuthbert may I ask what the status of this issue is? Thanks.

**Comment by mscuthbert** [comment]
I still don't think I'll be able to get to this anytime soon -- I think it's best to run midi files through a better MIDI -> MusicXML converter (musescore is scriptable) and load those first.

**Comment by jacobtylerwalls** [comment]
To disable MIDI quantization, use the keyword quantizePost=False.

Until now the keyword only worked on file names, not raw data.

Try renaming your file or setting forceSource=True so that you don't read the unwanted result back from disk, so:
`converter.parse('your_file_path.mid', forceSource=True, quantizePost=False)`

**Comment by smirkingman** [comment]
quantizePost=False doesn't always work, not all parsers implement the keyword.

The thing to understand is that **everything** has to be quantised to some extent in order to give the note a name. A note 0.25000 long is a crotchet, but if you don't round 0.24999999, it'll be a crotchet-with-just-hint-of-quaver.

It would be nice if we could say "use the default quarterLengthDivisors=(4, 3) to name the notes, but _don't quantise the offsets and durations_", but that doesn't seem possible, and probably questionable.

Setting quarterLengthDivisors=[128] produces reasonably unquantised results, but of course the notes will get names like "A in octave 2 Eighth tied to 16th tied to 64th tied to 128th tied to 512th (109/128 total QL) Note", which is unexpected and possibly humorous, but correct.

Don't over-do it though, quarterLengthDivisors=[4096] and the conversion takes forever.

**Comment by MauriceCalvert** [comment]
For those who stumble on this, here is the solution. converter.parse quarterlengthdivisors are specified in **_WHOLE NOTES_**, if you want to quantise down to 1/32 notes, with triplets, you need to write quarterLengthDivisors=(2, 3, 4, 8, 16, 32).

For example, if you quantise the end of the first bar of BWV772:
![image](https://github.com/user-attachments/assets/59e82749-d420-4928-8957-42103a3d9af2)
with the default quarterLengthDivisors=(4,3), the two C5-B4 get parsed as **two-note chords**.

With quarterLengthDivisors=(2, 3, 4, 8, 16, 32) you get what you expected.
