### ISSUE TITLE
Midi Translate methods assume channel 1 for NOTE_ON and NOTE_OFF

### ISSUE THREAD

**Issue by PeterMitrano** [cuthbertLab/music21#206]
It seems the `channel` is always set to 1 for `NOTE_ON` and `NOTE_OFF` events. Is this the case, or have I missed something? I'm trying to produce midi on two channels.

**Comment by mscuthbert** [comment]
If you choose different instruments or different tunings, then other channels can be specified. Hope that's helpful!

**Comment by PeterMitrano** [comment]
Are there any examples or documentation of how to specify the instrument for an element (note/chord/rest) in a stream? If not, is this project open to contributions of example code? I'm happy to give back once I figure it out.

**Comment by mscuthbert** [comment]
Of course; very happy to take in example code -- I think that there are examples in the instrument module, but not nearly as well done as we'd like, and unfortunately, no tutorial yet.

**Comment by PeterMitrano** [comment]
I'm ready to PR some examples. Things like "here's a snippet of code related to instruments... code ... explanations blah blah". Where would be appropriate to PR that?

Closing because I got it working

**Comment by mscuthbert** [comment]
Best would be in the documentation, after that it could go in the demos folder. But less important where: that can be moved. Just that it exists. :-)

**Comment by nightscape** [comment]
We've got a somewhat related problem:
We're trying to read a MIDI file generated by a [Jammy guitar](https://playjammy.com/).
The Jammy uses 6 MIDI channels for the 6 strings of the guitar.
We would like to retain this information during MIDI => Music21 transformation in order to e.g. do analysis later on how a chord was fingered.
Is there some way to transform MIDI into a Music21 stream without losing the channel information?

Thanks!
