### ISSUE TITLE
NameError in examples.ipynb

### ISSUE THREAD

**Issue by andrewsanchez** [cuthbertLab/music21#217]
```python
for m in violin2.getElementsByClass('Measure'):
    if len(m.notes) >= 8:
        break
m.show()

NameError: name 'violin2' is not defined
```
I'm just starting to work my way through the docs, so I'm sure it will become obvious how to fix this soon enough.

**Comment by mscuthbert** [comment]
Thanks!  The examples.ipynb used to be our main page for examples of how music21 worked, but it was too big and too advanced, so the "User's Guide" is now the main place to learn and I've been cannibalizing examples.ipynb for sections to use, and apparently didn't cannibalize this well enough.  I'll keep working through it this weekend, but the solution is probably to finally finish deleting the examples.ipynb so that it's in a section that gets tested.

**Comment by mscuthbert** [comment]
(fixed -- and docs are now tested!)
