### ISSUE TITLE
VexflowPickler corrupt json output?

### ISSUE THREAD

**Issue by mxordn** [cuthbertLab/music21#258]
Although it might also be related to music21j or jsonpickle I'm posting this issue here.

I encounter an error when using the generated html-output of the method `vexflow.toMusic21j.fromObject()` or `fromStream()`.
The content of the returned pickleIn variable seems to have too few information, because you have to add the item `"_elements": [],` to the stream description to get the output rendered. Otherwise fromPython.js returns an error with the s.append method. Is there a way to adapt the generated json output?

BTW: The cross-site scripts called from http://web.mit.edu/music21/music21j/src/music21 and http://web.mit.edu/music21/music21j/ext/require/require.js seem to be old ones. I have to use my local ones instead to get it running.

**Comment by mscuthbert** [comment]
ahhh!!! Yes, those are very old.  I will update them.

**Comment by mscuthbert** [comment]
Oh -- it turns out to be a substantially bigger change than I thought since the newer versions of music21j require full ES6 objects and not just (in old JS style) dicts that pretend to be objects; I'll need to leave this open for a bit since I don't have the time in the next few weeks to really dig into the jsonpickle guts, but any patches you might have would be appreciated.  Thank you!

**Comment by mscuthbert** [comment]
I've been thinking about this message off and on for 6 years now, and I think an entirely different approach (using music21j) is the only way that the vexflow directory is going to ever work.  When I come to music21 again after the sabbatical (or during) making graphical notation within music21-python will be a priority.

Closing as not-planned.  Sorry!
