### ISSUE TITLE
Wrong rest handling in time signature change

### ISSUE THREAD

**Issue by 00sapo** [cuthbertLab/music21#264]
It's simpler try this little code than explain the issue :)

```python
from music21 import stream, note, duration, meter
m1 = stream.Measure()
m1.append(note.Note('a'))
m1.append(note.Note('b'))
m1.append(note.Note('c'))
m1.append(note.Note('d'))
m1.number = 1

m0 = stream.Measure()
m0.append(note.Note('e', duration = duration.Duration(0.5)))
m0.append(note.Note('f', duration = duration.Duration(0.5)))
m0.number = 0
m0.timeSignature = meter.TimeSignature('4/4')

s = stream.Stream()
s.append(m0)
s.append(m1)

# s is a stream with anacrusis incipit:
print('orginal: ')
s.show('png')

# filling first measure of s with rests:

r = note.Rest()
r.duration.quarterLength = 3

for e in s.measure(0).recurse().notesAndRests:
    e.offset += r.duration.quarterLength

s.measure(0).insert(0, r)

print('padded: ')
s.show('png')

# changing time signature...
s.measure(0).timeSignature = meter.TimeSignature('1/4')

print('changed signature: ')
s.show('png')

print('after make measures: ')
s.makeMeasures().show('png')
```
Output is the following:

![image](https://user-images.githubusercontent.com/22996003/33524515-c2b0e3e6-d81e-11e7-9388-736003867d3a.png)

If you try with '2/4' instead of '1/4' and with 3 rests of 1.0 quarter length the issue persists and elements inserted at offset _**x**_ of a measure will be at offset _**x**_ of the whole stream after `makeMeasures()`. I think that the problem is with `insert` function.

**Comment by 00sapo** [comment]
The issue is dued to the fact that makeMeasures use measure offsets to reposition notes in the new stream. Using the following line, solves the problem:

`s.measure(1).offset += r.duration.quarterLength`

This behaviour is not intuitive in my opinion, but if there is no bug, maybe you could describe further the working of `makeMeasures()` in the docs.

**Comment by mscuthbert** [comment]
Make sure to look at what music21 is holding as the representation of the measures with incorrect time signatures not necessarily what your musicxml reader can generate -- a lot of XML readers cannot display music with incorrect time signatures.  try `.show('text', addEndTimes=True)` and see where the problem is.  In general, `.makeMeasures` is designed to create measures from streams without measures -- it is not designed to recreate existing measures.  You could do s.flat.makeMeasures() instead.
