### ISSUE TITLE
Music21 generates corrupt midis

### ISSUE THREAD

**Issue by Nintorac** [cuthbertLab/music21#305]
I am currently trying to transpose various midis into C using the script here `gist.github.com/aldous-rey/68c6c43450517aa47474`

I came across an issue where Music21 adds bytes > 127 into the midi file, as a result of this when trying to load the midi using mido the result is `OSError: data byte must be in range 0..127`. I have also tried to load the midi with clip=True but this throws out the timing of track

From the looks of it, music21 writes a bunch of pitchwheel events into the midi binary, which didn't exist in the original.

Is this a known issue? If necessary I can upload a before and after midi

Cheers

**Comment by stefanokalonaris** [comment]
I am having the same problem here. Loads of spurious additions, pitchwheel as well as timing problems.
Happy to post examples, too.

**Comment by mscuthbert** [comment]
Pitch bend/pitch wheel artifacts are to be expected -- music21 supports non-12-tone midi output; so long as all the pitch bend effects are (0, 64) they should not affect anything -- they just reset the wheel from any previous pitch bends.  

Note that MIDI does not have a standard for encoding non-ascii text, so that's the only place that I can imagine a > 127 byte character entering.

I would really need a minimal example pointing to the exact problem to investigate further.  I don't know mido and other MIDI systems play back music21 output fine.

(fixed: bug where pitch wheel events very close to zero (but not zero) produced incorrect pitch bends; almost certainly unrelated to these errors)

**Comment by mscuthbert** [comment]
Closing for lack of example.  Please reopen if a minimal example is found.
