### ISSUE TITLE
Please add requirements information to setup.py

### ISSUE THREAD

**Issue by yurivict** [cuthbertLab/music21#338]
Currently, it is hard to know what does it depend on.

**Comment by mscuthbert** [comment]
There are no external requirements to run music21.  If numpy, matplotlib, scipy, and some other modules are installed (or if MuseScore or Lilypond are also installed) then then additional functionality is unlocked, but we haven't made them requirements since the installation should not fail if they are not installed.  If there's a way to make them install by default but not cause the installation to fail without them then I'd love to do that, but haven't seen how.

**Comment by yurivict** [comment]
> If numpy, matplotlib, scipy, and some other modules are installed

There is also a way to specify optional dependencies in ```setup.py```. I sometimes define the port option ```OPTIONAL``` and based on it install them. Without the list it is hard to know what are they.

**Comment by AlmogCohen** [comment]
It was indeed weird to see no dependencies anywhere (and I was searching for it for a while), yet understandable when I saw @mscuthbert answer. Is it possible indeed to list somewhere the optional ones? Maybe even as a comment in the `setup.py` file like @yurivict suggested above?

**Comment by AlmogCohen** [comment]
Cause I couldn't figure out the the requirements were actually nothing...while it is very nice to find this out here

**Comment by mscuthbert** [comment]
Requirements.txt changed in v6 -- closing, but feel free to reopen or comment if still a problem.
