### ISSUE TITLE
cannot translate to lilypond when stream contains grace notes

### ISSUE THREAD

**Issue by gesellkammer** [cuthbertLab/music21#343]
Whenever a stream contains grace notes, music21 fails with "LilyTranslateException: Cannot translate an object of zero duration <music21.duration.GraceDuration unlinked type:zero quarterLength:0.0>" when trying to do stream.show('lily.pdf') (or lily.png)

**Comment by giamic** [comment]
Hi, I have had the same problem. I've found a hack to ignore grace notes, which is acceptable in my case. Of course, a solution to the bug would be preferable.

The hack. Inside the file music21/lily/translate.py, go to the function `appendContextFromNoteOrRest(self, noteOrRest)` (defined in lines around 1100-1200) and add the following two lines before everything else
```python
if noteOrRest.duration.isGrace:
    return
```

**Comment by mscuthbert** [comment]
Thanks!  Fixed in next version.  @giamic  is on a roll!

**Comment by gesellkammer** [comment]
This is not a solution. It just ignores the problem and, even worse than the original bug, fails silently. Please reopen

**Comment by mscuthbert** [comment]
It is not worse than the original since it doesn't crash.  Music21 shouldn't crash.

Just to note, I'm not developing any further Lilypond translations -- and will be removing Lilypond output in the next version if a Lilypond for Mac OS X 64-bit is not released.  So it's likely never to be fixed.  If someone is willing to pay for consulting (https://web.mit.edu/music21/doc/about/faq.html) or contribute a fix, then it'll be merged.  But just to note that this is not a paid software product; there is no support staff, just a community of people interested in improving it.

**Comment by giamic** [comment]
I agree with gesellkammer that this is not a real solution, just a hack that can sometimes be useful. Maybe one should at least log a warning when invoking stream.show() or stream.write() that grace notes are being ignored?
