### ISSUE TITLE
tempo information not used for playback in Jupyter notebook

### ISSUE THREAD

**Issue by leoauri** [cuthbertLab/music21#353]
Hi, I expected the following to set the tempo for the rendered MIDI:

```
output = music21.stream.Stream()

tempo = music21.tempo.MetronomeMark(number=176)
tempo.numberSounding = 176
output.append(tempo)

# append Notes to Stream

output.show('midi')
```

I also tried embedding this in a Score object:

```
score = music21.stream.Score()
tempo = music21.tempo.MetronomeMark(number=176)
tempo.numberSounding = 176
score.append(tempo)

output = music21.stream.Stream()

# append Notes to Stream

score.append(output)

score.show('midi')
```

But playback tempo remains unaffected.  Am I doing this wrong?  
Couldn't find any reference in the documentation...

Thanks, looks like a great library

**Comment by jacobtylerwalls** [comment]
heya @leoauri thanks for the report -- can you retry on v.6.1. and let us know if this is still an issue? when I run your code outside of Jupyter I get a midi file that Garage Band loads with the correct tempo, and there have been Jupyter <-> MIDI changes since your report. good luck and let us know!

**Comment by mscuthbert** [comment]
Pinging @leoauri again -- I think that this has been fixed.  Please reopen if still a problem.  Thanks for the compliments!
