### ISSUE TITLE
Consider making a no-corpus version also available via pip

### ISSUE THREAD

**Issue by p-himik** [cuthbertLab/music21#387]
Just what the title says.
Also relevant: #172

**Comment by mscuthbert** [comment]
Happy to take a PR on this, but unlikely to get onto my priority list.  The no-corpus version is designed for OS release people to be able to include it w/ their operating systems.  It's not something I would ever want to encourage people to use.  Let me know if you plan to work on it, otherwise I'll need to close for lack of time.

**Comment by p-himik** [comment]
I see, thanks. I'm unlikely to have time for this as well - at this point, it's easier for me to just remove the corpus once it's downloaded.
