### ISSUE TITLE
Additional General MIDI Instrument Support

### ISSUE THREAD

**Issue by bzier** [cuthbertLab/music21#397]
Relating to the discussion in #235, I encountered issues reading midi files which utilize guitar instruments. Because there were no instrument definitions for some of the general midi standards, the translated stream was loaded with piano tracks (which is the default instrument). @mscuthbert, you mentioned that not all instruments should necessarily have a definition. I'd to understand that a little better. When translating midi to stream, the instrument is loaded by ID. In the case that the ID is not found, it falls back on the piano. It seems in order to properly maintain the correct instrument when translating to/from midi/streams, it would need a definition. Since I'm still new to and learning music21, there may be some gap in my understanding, so please correct me if I am wrong. If an instrument definition is not the right approach, what else can be done in order to support proper handling of these files? I'm happy to implement whatever solution you'd suggest and submit the PR. Thanks.

**Comment by bzier** [comment]
@mscuthbert ping

**Comment by bzier** [comment]
I just bumped into a similar issue with specific piano instruments (e.g. Honky Tonk Piano) which are also not defined in `Instrument.py`. I'd like to better understand why certain standard instruments in General Midi would not be explicitly supported by this library. Thanks.

**Comment by mscuthbert** [comment]
Hi @bzier -- sorry for so long a wait.  Basically, we will not create a different instrument for something that is a sound element of a particular instrument.  For instance, Pizzicato Strings -- you can't go to a store and say, "Hi!  I'd like so pizzicato strings" -- so that will never be an instrument object in music21 -- that can be something else like a sound change object or something like that. Similarly with Guitar Fret Noise.  A HonkyTonkPiano is a Piano with the midi patch set to a different program number than the default piano and maybe a different name.  There are many corner cases, and we'll need to address those.  So this is a good place to hold that discussion.  I probably wont' get to this till the summer -- my other job has to take priority.  But happy to take PRs etc.

**Comment by JuanuMusic** [comment]
SO, Im interested on helping out with this issue, which could also fix #398 but first need to understand a few things.

I already have the latest code.
 I was trying to get instrument from a MIDI file that has 5 program_change events, but on the stream received, when trying to retrieve the instruments it returns  None.

```

from music21 import midi, instrument

file = midi.MidiFile()
file.open('./midi_files/1.mid')
file.read()
file.close()
score = midi.translate.midiFileToStream(file)

instrument = score.getInstrument(returnDefault=False)
print('Instruments', instrument)


OUTPUT
Instruments None
```

Ive been debuging the code, and see that `INSTRUMENT_CHANGES `are parsed correctly, and added to the `metaEvents `of the `Stream`. The problem is that at some point, along the way of calling `midiFileToStream()`, and returning the `Stream`, those events get lost, or removed or something like that.

Any clues?

**Comment by JuanuMusic** [comment]
Adding more on the subject, I found that some midi files can be made with a Single Track, with multiple instruments, thus having to implement a method to load the Instruments based on their CHANNEL.

**Comment by mscuthbert** [comment]
Hi @JuanuMusic -- I think that your cases are enough different from the problem here that it should be moved off of this issue, which is about adding more instruments connected to General MIDI; not about MIDI parsing in music21.

**Comment by rmapes** [comment]
Re adding more instruments, @mscuthbert , if I understand your concerns, you're saying that an Instrument should represent a distinct playable object, whereas general midi instruments often represent different ways of playing the same instrument (e.g. muted trumpet vs trumpet). Would it therefore make sense to introduce a Sound object, sitting within an Instrument, which represents the information described by a general midi instrument?
There's then a question about whether e.g. a Honky Tonk Piano vs a Grand Piano represent different insruments, or different set ups of the same instrument, but that just becomes an organizational challenge rather than a technical one.
For full disclosure, my ultimate aim here would be to be able to load a midi file in and then save it back without data loss. My current problem is trying to isolate out the piano parts when loading in midi ragtime with bass and percussion, and this is currently being lost if midi programs 1-5 are used rather than 0

**Comment by jacobtylerwalls** [comment]
hi @JuanuMusic see #686 for the latest efforts toward the issue you discussed in your first comment. Have a look and leave feedback if you like.
Cheers, Jacob
