### ISSUE TITLE
getContextByClass() quirks

### ISSUE THREAD

**Issue by a-papadopoulos** [cuthbertLab/music21#400]
It seems that `getContextByClass()` doesn't always work as expected depending on the order of insertion. For example, if I do the following:
```python
from music21.stream import Measure
from music21.note import Note
from music21.harmony import ChordSymbol

m = Measure()
m.insert(0, Note('C'))
m.insert(0, ChordSymbol('Am'))
m.notes[0].getContextByClass(ChordSymbol)
```
the last call doesn't return anything. However, if I do the two inserts the other way around, I do get the chord symbol:
```python
m = Measure()
m.insert(0, ChordSymbol('Am'))
m.insert(0, Note('C'))
m.notes[0].getContextByClass(ChordSymbol)
```
This seems at odds with the documentation of getContextByClass(). In particular, if I run `m.getElementAtOrBefore(0, classList=[ChordSymbol])`, in both cases it returns the ChordSymbol.

**Comment by mscuthbert** [comment]
Is this on Py3.5 or a later version?  Some context searches occasionally fail on Py3.5 and I'm just waiting until it goes EOL rather than fixing those.

But this could be an uncaught error -- I don't think I've tested having two non-zerowidth objects at the same offset and trying to get a context at the same location but "later" in the stream.

**Comment by a-papadopoulos** [comment]
I'm on python 3.6.5

Anyway, it's good to have the confirmation that this is unexpected. I will try to make sure ChordSymbol always happen first and that'll do as a workaround for the time being -- I tried to dive a bit into that piece of code, and it does look scary :)

**Comment by mscuthbert** [comment]
I'll have to think if it's unexpected and read through the docs and then figure out if the solution is to change the implementation (some of the most difficult code in the music21) or change the docs.  :-)  So good to make sure that the ChordSymbol comes first.  Obviously for note and chordSymbol at the same time, it makes sense that the Note's ChordSymbol context includes the ChordSymbol.

Actually, thinking through it -- there's an easier solution: Harmony objects should have a lower CLASS_SORT_ORDER than notes, chords, etc., so that they appear at the same offset with the same priority, they always go first.  That's the easy and correct solution.

**Comment by a-papadopoulos** [comment]
Awesome, thanks!
