### ISSUE TITLE
DynamicWedges

### ISSUE THREAD

**Issue by MarkGotham** [cuthbertLab/music21#447]
Recurring issue with importing dynamic wedges for cases without the ‘stop’ specified.

File:
music21/music21/musicxml/xmlToM21.py

Line:
3604

Section:
xmlDirectionTypeToSpanners

Error message:
music21.musicxml.xmlToM21.MusicXMLImportException: Error in getting DynamicWedge

**Comment by mscuthbert** [comment]
Is the Stop required by XML specification (I believe the answer is yes) -- if so what should the correct behavior be?  I can imagine several cases:

(1) the wedge is dropped from the score
(2) the wedge continues until the end of the score (this will raise other problems since XML only allows 6 simultaneous wedges, so it will just push the problem to the output side).
(3) wedge continues until first rest (might have the same problem as (2) and require a lot of additional coding)
(4) raise more specific error and refuse to parse the score (as now).

The best approach (wedge continues till end of measure) would actually be the most difficult of all to implement, so I'm not listing it (since I wouldn't be willing to write the code needed to do that).

Thanks!

**Comment by MarkGotham** [comment]
Thanks Myke!

For my current purposes (batch score processing with no interest in dynamics), I would vote for option 1. I’ve adapted my copy of m21 to that effect.

Even if I were working with dynamics I think I’d find it a bit heavy handed to fail the parse because of one or two of these (as is often the case).

As an alternative to end-of-measure, would a fixed arbitrary quarter length / number of notes be easier?

Anyway, that’s my 2cents; I can’t speak for the whole community, of course.

**Comment by giamic** [comment]
Hi, I've encountered this problem already many times. I agree with Mark there, dropping the wedge seems like the most reasonable thing to do. But I would add a warning so that one could identify the offending notation and correct it.

**Comment by mscuthbert** [comment]
which software is generating the problematic wedges?

**Comment by giamic** [comment]
I can't really say, I rarely write my own musicxml files from scratch. All I can say is that musescore 3 doesn't seem to automatically correct them when exporting to a new file.

**Comment by GLN** [comment]
The refusal to parse the score on an offending wedge or two is quite problematic for my use case, and dropping the wedge is not ideal since I care about the dynamic content of the MusicXML file. I have filed a previous issue on this, FWIW. Here's hoping?

**Comment by mscuthbert** [comment]
Why not fix the software creating the incorrect XML instead?

**Comment by mscuthbert** [comment]
I think this was fixed in #473

**Comment by MarkGotham** [comment]
Great, thanks!
