### ISSUE TITLE
Endings that repeat are not parsed correctly.

### ISSUE THREAD

**Issue by grotcadiz** [cuthbertLab/music21#490]
Example: test3.musicxml  repeats 3 times and has 2 different endings. The first ending(measure 2) repeats twice. The second ending(measure 3) repeats once. 

The musicxml file : [test3.zip](https://github.com/cuthbertLab/music21/files/3873523/test3.zip)

However when parsed into python using:

`test = converter.parse('test3.musicxml')` 
`test.show('t')`
`test.expandRepeats()`

the information that the first ending repeats twice is lost.  This means that the repeat expander returns an error when used on the stream. 

`ExpanderException: cannot expand Stream: badly formed repeats or repeat expressions`

**Comment by mscuthbert** [comment]
Is the problem that the musicxml is not being imported properly so that the Repeat expressions showing repeats 1-2 and ending 3 are not appearing in music21 after `.parse()` or that expandRepeats is not expanding them?

**Comment by grotcadiz** [comment]
It's not imported properly. 
![image](https://user-images.githubusercontent.com/25702733/69815892-46942480-1232-11ea-8e18-f6bd488bf9df.png)

**Comment by jacobtylerwalls** [comment]
greetings @grotcadiz 

I believe the repeat expander is spitting exceptions at you because you need to call it on the part, not the score, which you can solve by just calling `recurse()`.

```
>>> s.recurse().expandRepeats().show('t')
{0.0} <music21.metadata.Metadata object at 0x7fb07b98dd10>
{0.0} <music21.instrument.Instrument 'P1: MusicXML Part: '>
...
```

Now, you still have a point that M21 is not reading multiply-numbered endings from XML, specifically: comma-separated values such as `endings="1, 2"`.

The good news is that there is robust functionality for spanner endings that xmlToM21 isn't trying to take advantage of, and I think it's a three-line fix.
