### ISSUE TITLE
Unexpected behavior in TransposePitch using reversed=True

### ISSUE THREAD

**Issue by punyidea** [cuthbertLab/music21#524]
Environment: 
music21 5.7.2
Python 3.5
Mac OS

The reverse flag is ignored in a DiatonicInterval, as I confirmed with my Python debugger.

Minimal reproducing code:
 
    start_pitch=pitch.Pitch('A4')
    p8 = m21.interval.Interval(12.0)
    p8.transposePitch(start_pitch,reverse=True)

I am almost certain this is due to the following code snippet inside of the transposePitch method:

        if self.implicitDiatonic:
            # this will not preserve diatonic relationships
            pOut = self.chromatic.transposePitch(p)
        else:
            pOut = self._diatonicTransposePitch(p, reverse, maxAccidental)

Given that the reverse parameter is not documented in this method, perhaps this is expected behavior? But I believe this should still be explicitly stated, and brought up in the Interval documentation.

Thanks for taking the time to review this issue! I like the framework that this library sets up.

**Comment by mscuthbert** [comment]
This is one of the best issue descriptions I've ever seen -- thank you!  I didn't really have time to fix it now, but I knew it needed to be fixed and just did it before it bugged me.

Having `reverse=True` is a relic -- that was never going to work in every situation an interval can find itself in.  So instead the method now calls `self.reverse()` and performs the transposition on that new interval.  It sets one failure point instead of many different ones.

Thanks.  Once PR #525 passes, it'll be merged in and make it out in time for v6.  Thanks Victor Prieto!

**Comment by punyidea** [comment]
Wow, what a lightning fast response! Glad I could be of help. 

Your fix also seems reasonable. In fact, my current workaround is simply to use 
    p8.reverse().transposePitch

:)

**Comment by mscuthbert** [comment]
Ha!  Great minds!

**Comment by mscuthbert** [comment]
I'm going to start pointing people to this Issue on how to write one that gets my attention.
