### ISSUE TITLE
music21.exceptions21.StreamException: cannot place element 

### ISSUE THREAD

**Issue by plog** [cuthbertLab/music21#534]
Hi, 

**How to reproduce:**
I reproduced the problem using:

```
m21mid = converter.parse("1-Midi.mid")
measures = m21mid.measures(0, None)
```
**Midi file example:**
I simplified the Midi received by my colleague as much as poss (I'm not MuseScore expert)

[1-Midi.mid.zip](https://github.com/cuthbertLab/music21/files/4552127/1-Midi.mid.zip)

<img width="300" src="https://user-images.githubusercontent.com/26974/80606092-114c6680-8a5e-11ea-8511-c407cf07efae.png">

**Result:**
> Traceback (most recent call last):
> [...]
>   File ".../venv/lib/python3.7/site-packages/music21/stream/makeNotation.py", line 577, in makeMeasures
>     'within any measures' % (e, start, end))
> music21.exceptions21.StreamException: cannot place element <music21.tempo.MetronomeMark adagio Quarter=56.0> with start/end 3.0/3.0 within any measures

Thanks for Music21 !! 👍🏻

**Comment by mscuthbert** [comment]
I thought that the problem was that "gracenote" but not really gracenote E at the end -- it's durationless.  
```
In [25]: s = converter.parse('~/Downloads/1-Midi.mid')                          

In [26]: s.show('text', addEndTimes=True)                                       
{0.0 - 3.0} <music21.stream.Part 0x12194a3d0>
    {0.0 - 0.0} <music21.instrument.Piano 'Piano'>
    {0.0 - 0.0} <music21.tempo.MetronomeMark animato Quarter=120.0>
    {0.0 - 0.0} <music21.key.Key of C major>
    {0.0 - 0.0} <music21.key.Key of C major>
    {0.0 - 0.0} <music21.meter.TimeSignature 3/4>
    {0.0 - 3.0} <music21.note.Rest rest>
    {3.0 - 3.0} <music21.tempo.MetronomeMark adagio Quarter=56.0>
    {3.0 - 3.0} <music21.note.Note E>
```
If it were the problem, then I might not fix.  BUT, removing the note still has the same problem, so I needed to investigage further.

It turns out that here's a minimal code sample that reproduces the problem:
```
insert_point = 3.0
test_obj = base.Music21Object()

p = stream.Part() 
p.append(meter.TimeSignature('3/4'))
p.insert(insert_point, test_obj)
p.measures(0, None)
```

creating this minimum code sample took all my music21 coding for today.  I see that if insert_point is a multiple of the full bar duration (but not zero) it fails. If test_obj is assigned a duration > 0 then it works.  So I'll start again from there next chance I can.
