### ISSUE TITLE
Lilypond converter produces invalid color statements

### ISSUE THREAD

**Issue by chrisspen** [cuthbertLab/music21#541]
If you set any custom `note.style.color = "#00FF00"` attributes in your score, and then export these using the `ConverterLilypond` backend, these are written to the file as:

    \color "#00FF00" e' 4

which doesn't appear to be a valid format, and is ignored by Lilypond, resulting in a black and white image.

I believe the correct syntax is:

    \override NoteHead.color = #(rgb-color 0 1 0)
    \override Stem.color = #(rgb-color 0 1 0)
    e' 4

**Comment by mscuthbert** [comment]
Lilypond support is currently deprecated and was scheduled to be removed from music21 whenever it is I upgrade my test system to MacOS Catalina because the developers did not create a 64-bit version for Mac. However, it looks like a few months ago there's now an "unofficial" 64-bit application so I will not make any move towards removing Lilypond. However, I'm highly unlikely to devote any more (non-paid) development time to Lilypond; but happy to take well-tested patches to add features etc.

**Comment by mscuthbert** [comment]
As there is now decent 64-bit builds (even if unofficial), Lilypond support is no longer deprecated.  But it's not something I'm going to be working on for now.
