### ISSUE TITLE
converter.parse fails on zero-track MIDIs

### ISSUE THREAD

**Issue by eddsalkield** [cuthbertLab/music21#569]
When calling `music21.converter.parse` on a zero-track MIDI, an `IndexError` is returned because there is no 0th Stream.

```
>>> import music21
music21: Certain music21 functions might need these optional packages: matplotlib, numpy, scipy;
                   if you run into errors, install them by following the instructions at
                   http://mit.edu/music21/doc/installing/installAdditional.html
>>> music21.converter.parse('blank.mid')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/pi/.local/lib/python3.7/site-packages/music21/converter/__init__.py", line 1129, in parse
    forceSource=forceSource, **keywords)
  File "/home/pi/.local/lib/python3.7/site-packages/music21/converter/__init__.py", line 1009, in parseFile
    v.parseFile(fp, number=number, format=format, forceSource=forceSource, **keywords)
  File "/home/pi/.local/lib/python3.7/site-packages/music21/converter/__init__.py", line 544, in parseFile
    self.parseFileNoPickle(fp, number, format, forceSource, **keywords)
  File "/home/pi/.local/lib/python3.7/site-packages/music21/converter/__init__.py", line 478, in parseFileNoPickle
    self.subConverter.parseFile(fp, number=number, **keywords)
  File "/home/pi/.local/lib/python3.7/site-packages/music21/converter/subConverters.py", line 982, in parseFile
    midiTranslate.midiFilePathToStream(fp, self.stream, **keywords)
  File "/home/pi/.local/lib/python3.7/site-packages/music21/midi/translate.py", line 1975, in midiFilePathToStream
    return midiFileToStream(mf, inputM21, **keywords)
  File "/home/pi/.local/lib/python3.7/site-packages/music21/midi/translate.py", line 2115, in midiFileToStream
    **keywords)
  File "/home/pi/.local/lib/python3.7/site-packages/music21/midi/translate.py", line 1905, in midiTracksToStreams
    p = s.getElementsByClass('Stream')[0]
  File "/home/pi/.local/lib/python3.7/site-packages/music21/stream/iterator.py", line 328, in __getitem__
    e = fe[k]
IndexError: list index out of range
```

**Comment by jacobtylerwalls** [comment]
heya @eddsalkield 

From your traceback it looks like there were tracks in the midi file, since we made it to `midiTracksToStreams` without short-circuiting on this:
https://github.com/cuthbertLab/music21/blob/f54631b456788813d7d583da6d29e9977022e1af/music21/midi/translate.py#L2106

Now, I actually stumbled across this trying to repro a different Github issue, so can you provide the output from running this on your source:

```
mf = music21.converter.midi.MidiFile()
mf.open('blank.mid')
mf.read()
mf.close()
mf.tracks[0].hasNotes()
mf.tracks[1].hasNotes()
```
If either of those are False, then we need the type and velocity of any of the NOTE_ON messages in the `mf.events` array in order to look into this. Thanks

**Comment by jacobtylerwalls** [comment]
Looked into this after working on a MIDI export features.  This is a legit but rare issue with MIDI import. m21 will crash if there is no MIDI track with notes and therefore no Stream 0 in the stream iterator, at least according to `MidiTrack.hasNotes()`. But we don't need to get the Stream at index 0 since we should really be putting `MetronomeMarks` in every part:

https://github.com/cuthbertLab/music21/blob/f54631b456788813d7d583da6d29e9977022e1af/music21/midi/translate.py#L1902-L1911

Refactoring this a little bit will take care of this. At the same we can address this TODO:

https://github.com/cuthbertLab/music21/blob/f54631b456788813d7d583da6d29e9977022e1af/music21/midi/translate.py#L1893-L1896

**Comment by eddsalkield** [comment]
Thanks for working on this!  Sorry that I haven't provided the output from running this on the source MIDI; I was using a friend's machine, and we're now in physically separate locations.  Would the output still be useful to you?

**Comment by jacobtylerwalls** [comment]
Maybe! Depends on if you expected your MIDI file to be "empty" or not. It looks like your track had tracks, but was empty of notes. If so, then I don't need to see it. If, however, you thought it was supposed to have notes, and then music21 didn't find any notes, then I wanna see it.

**Comment by jacobtylerwalls** [comment]
If you do decide to run this, then even more informative than just printing `.hasNotes()` would be printing the `.events` array on each `MidiTrack`. But like I said, if you expected your file to lack any notes at all, then we're good.

**Comment by mscuthbert** [comment]
I'm going to need to wait for the (next) weekend to get my head around Conductor Tracks -- it's looking really good but I want a clear headspace and hard to do at start of term.
