### ISSUE TITLE
Enharmonic spelling for seventh chords in commonName

### ISSUE THREAD

**Issue by zgowani** [cuthbertLab/music21#614]
The chords library has some trouble naming certain chords. For example:

```
>>> import music21
>>> notes = ['C', 'D#', 'G', 'A#']
>>> c = music21.chord.Chord(notes)
>>> c.pitchedCommonName
'A#-minor seventh chord'
```

That above chord should be a C minor seventh chord (Source: https://www.pianochord.org/cm7.html). The guess from the chords module is quite off -- A#-min7 actually contains an A#, C#, F, and G#. (Source: https://www.pianochord.org/am7-sharp.html)

If we replace the sharps with flats in the input, music21 gives the right answer.
```
>>> notes = ['C', 'Eb', 'G', 'Bb']
>>> c = music21.chord.Chord(notes)
>>> v
>>> c.pitchedCommonName
'C-minor seventh chord'
```

Tested with Python 3.8.5, Music21 v6.1.0.

PS: Thanks for your hard work I love this library :)

**Comment by jacobtylerwalls** [comment]
heya @ZakirG thanks for the report. I'll let MSC chime in, but it isn't totally clear to me what music21 should do here, since that's only a minor seventh chord at all if we're not being strict about spelling, but that's only an A# rooted chord if we're being 100% strict about spelling. We're mixing ideas about enharmonic strictness.

One solution might be: before `root()` exits, if a diminished third is present in the chord, call `bestPitches()` and then find the root of a chord made of THOSE pitches and respell the root if necessary.

Another solution would be to fail loudly in `pitchedCommonName`, perhaps setting a flag when loosely spelled chords are being tolerated to derive a `commonName` and use that to return some kind of `pitched common name cannot be derived -- try bestPitches()`

**Comment by mscuthbert** [comment]
pitchedCommonName has some flaws -- the chord is neither an A#-minor-seventh-chord nor a C-minor-seventh-chord is should be reported as "forte class 4-26 above C" since music21 should not be reporting tonal structures for chords that are not spelled correctly.  See for instance try pitchedCommonName on C, F-, G or C D## G-- it does not say that it is a C major chord, but enharmonically equivalent to a major triad above C.  Changing to F-4 G4 C5 will say that it is "above F-"

TODO: add enharmonic checks for all common seventh and some ninth chords and sus chords.

music21 operates in a tonal/spelling-matters context for many basic operations.

**Comment by mscuthbert** [comment]
thanks for both the bug report and the compliment, @ZakirG!

**Comment by ZakirG** [comment]
It's true that the notes in my example, though enharmonically equivalent, are technically a misspelling of C minor 7 relative to the key signature. But I disagree with the conclusion here.

The set of notes in my example represent a common and foundational chord voicing. Logic Pro X, in contrast to music21, will reports these notes as a C minor 7 chord, no matter what global key is set in the project file. And it will do so with MIDI data alone. MIDI numerals do not distinguish between Eb and D#. See here: https://www.inspiredacoustics.com/en/MIDI_note_numbers_and_center_frequencies

Every chord has multiple possible names, but the name reported by a music tool should be the one most useful to a human user (I would argue that "forte class 4-26 above C" is not the most useful chord name in this situation). 

It seems to me that this chord module will not work well in situations where the key signature is unknown or irrelevant. Which makes it tough to use in programs that work with MIDI files or generative music.

**Comment by jacobtylerwalls** [comment]
Have a look at this:
```
>>> notes = [60, 63, 67, 70]
>>> c = chord.Chord(notes)
>>> c.pitchedCommonName
'C-minor seventh chord'
```

I think it's a top-notch feature of music21 that you can work with MIDI data if you don't care about spelling, and you can work with the exact symbolic data generated or parsed from a representation of sheet music if you do, and you even have easy ways to convert between the two.

**Comment by ZakirG** [comment]
Wow awesome! I didn't know about that. That fits my use case perfectly. Thanks =)

**Comment by jacobtylerwalls** [comment]
No problem. Don't forget to hit up `.midi` on any `Pitch` object.

**Comment by mscuthbert** [comment]
Note that pitches have a `.spellingIsInferred` attribute which if set to True means that the exact spelling (C# vs. Db etc) was inferred from a numerical context and routines such as transpose('m2') are free to change the spelling of the pitch of the note as it fits the context.  note.Note(61) would set spellingIsInferred to True.   

The initial bug still stands, so keeping this issue open.

**Comment by natepmay** [comment]
Came here because I discovered the same bug re: enharmonic spellings of minor sevenths. In my case
```
myChord = chord.Chord(["F", "G#", "C", "D#"])
print(myChord.pitchedCommonName)
>>> D#-minor seventh chord
```
I'm not sure where it got that, but I would love for it to return "enharmonic equivalent of F minor seventh chord" (but not just "F minor seventh chord" as suggested—I'm glad that spelling matters).
