### ISSUE TITLE
Can chords be hashable? 

### ISSUE THREAD

**Issue by napulen** [cuthbertLab/music21#695]
I was just wondering if there is a good reason why `Chord` objects don't have a `__hash__` function? They already seem to have `__eq__`.

If this is an acceptable idea, would something like this do?
```python
def __hash__(self):
    hashValues = (
        self.pitchNames,
        # maybe something else
    )
    return hash(hashValues)
```

**Comment by mscuthbert** [comment]
Chords are built on notes and pitches -- they are both mutable objects so they're unhashable.  The eq operation takes place at the time of comparison, so generally someone can trust that at that moment they are equal.  Hash functions are designed to be stored to check later (quickly) whether two objects are equal.  Because from the time of the hashing to the moment when the hash value has been retrieved the object may have changed, we provide no hash function for them.
