### ISSUE TITLE
Missing attribute secondaryRomanNumeralKey in music21.roman.RomanNumeral documentation

### ISSUE THREAD

**Issue by napulen** [cuthbertLab/music21#711]
In the documentation entry for [RomanNumeral](https://web.mit.edu/music21/doc/moduleReference/moduleRoman.html), the `.secondaryRomanNumeralKey` attribute is not described, however, it is available as of `v6.3.0` (probably introduced since `v6.1.0` or before).

Probably missing a `doctest` entry for this attribute somewhere in the code.

**Comment by jacobtylerwalls** [comment]
heya @napulen I'm seeing a handful of doctests, this one plus another nested V42/V7/vi just below. Did you have a specific suggestion for ordering?

https://github.com/cuthbertLab/music21/blob/42ff5b52602cad3f45412fe1fb1640d428c22648/music21/roman.py#L1305-L1306

**Comment by mscuthbert** [comment]
So MANY missing docs here.  Working on them all -- will have a patch very soon!

**Comment by mscuthbert** [comment]
Fixed in #713  Thanks Néstor for the prompting.  I'm uploading the docs now -- there are a few things that have changed in next version so the docs don't 100% match 6.3 release, BUT they're minor enough and only apply to very unusual cases (such as `roman.RomanNumeral('')`  ) that I don't think it's a big deal to have new docs up.

**Comment by mscuthbert** [comment]
The attribute's been around at least since v2! and possibly v1.  :-O

**Comment by napulen** [comment]
Thanks @mscuthbert! I have been working on a project and I am trying to report anything I see as I go!
