### ISSUE TITLE
developerReference documentation: avoiding sphinx formatting

### ISSUE THREAD

**Issue by MarkGotham** [cuthbertLab/music21#790]
In the [developerReference documentation for documenting](http://web.mit.edu/music21/doc/developerReference/documenting.html), there's an example for how to avoid sphinx formatting which claims:
- line breaks and spacing is preserved
- bold sphinx formatting is not observed

... but the bold still seems to be observed in the example and as that's the only expected change, it looks likely that it's all simply still formatted.

No PR because I'm out of my depth here but some thoughts based on the instructions:
- Space(/s) before after (possibly missing, though there are line breaks)
- (Related) position of the double colon

Screenshot:
<img width="818" alt="BoldIsObserved" src="https://user-images.githubusercontent.com/19486660/105630471-595bb680-5e41-11eb-96be-7b76702625c9.png">

**Comment by jacobtylerwalls** [comment]
Good catch, this was a bit of a pretzel. The example used an apostrophe, so everything after "I'm" came out wrong, plus the line breaks didn't match. And the demonstrated result should have been block-quoted with two colons as promised so that it displayed correctly. Python keywords like "for" and "is not" were also being semi-bolded. New screenshot in PR.

**Comment by MarkGotham** [comment]
Happy to help; thanks for resolving so fast!
