### ISSUE TITLE
"pip --upgrade" installs old version 1.9.3

### ISSUE THREAD

**Issue by maxalbert** [cuthbertLab/music21#88]
By default, `sudo pip install --upgrade music21` installs the old version 1.9.3, even though version 2.0.0 is already [available on Pypi](https://pypi.python.org/pypi/music21/2.0.0) and the `--upgrade` flag should force installation of the latest version. When run with multiple `-verbose` flags, pip's output has a bunch of lines like the following:

```
Not searching https://github.com/cuthbertLab/music21/releases/download/v2.0.0/music21-2.0.0.tar.gz#md5=60183b92885d7ed4176f712e4c8f75b3 (from https://pypi.python.org/simple/music21/) for files because external urls are disallowed.
```

So the issue seems to be that the tarball is externally hosted on Github and pip by default does not allow installation from remote locations. Indeed, the following command fixes the issue and updates to the latest version:

    sudo pip install --upgrade --allow-all-external music21

Can this be fixed somehow, e.g. by uploading the latest tarball to PyPI? 

One of the problems with the older version 1.9.3 is that IPython notebook integration is broken: `stream.show()` only gives a cryptic Javascript error instead of displaying an image of the notes. However, there is almost no way to trace the error back to the fact that it's not the latest version (it took me a good few hours to debug this, and I only discovered it by chance when comparing with a working installation on a different computer).

Many thanks!

**Comment by mscuthbert** [comment]
The problem is that PyPI has a max of 50MB upload size so we can't generally host there because the file size keeps fluctuating above the limit.  I don't want to distribute the no-corpus version (9MB saved) because it's very important to me that music21 comes "batteries included".  But here are a list of files some of which I can remove or trim down for the future.  The TIFFs and the WAV don't compress:

-rw-r--r--  0 cuthbert staff    16196 Jun 27  2014 music21-2.0.0/music21/webapps/client/cognition/mitlogo.png
-rw-r--r--  0 cuthbert staff    17541 Jun 27  2014 music21-2.0.0/music21/webapps/client/javascript/json2.js
-rwxr-xr-x  0 cuthbert staff    17541 Jun 27  2014 music21-2.0.0/music21/webapps/archive/client/musescore/music21/json2.js
-rwxr-xr-x  0 cuthbert staff    17541 Jun 27  2014 music21-2.0.0/music21/webapps/archive/client/musescore/music21theoryAnalyzer/json2.js
-rw-r--r--  0 cuthbert staff    17753 Jun 27  2014 music21-2.0.0/music21/midi/testPrimitive/test09.mid
-rw-r--r--  0 cuthbert staff    20931 Jun 27  2014 music21-2.0.0/music21/webapps/archive/client/musescore/music21theoryAnalyzer/data/Image.jpg
-rw-r--r--  0 cuthbert staff    22287 Jun 27  2014 music21-2.0.0/music21/webapps/archive/client/hackdaydemo/images/img3.jpg
-rw-r--r--  0 cuthbert staff    22287 Jun 27  2014 music21-2.0.0/music21/webapps/archive/client/hackdaydemo/img3.jpg
-rw-r--r--  0 cuthbert staff    22411 Jun 27  2014 music21-2.0.0/music21/webapps/archive/client/hackdaydemo/images/img5.jpg
-rw-r--r--  0 cuthbert staff    22411 Jun 27  2014 music21-2.0.0/music21/webapps/archive/client/hackdaydemo/img5.jpg
-rw-r--r--  0 cuthbert staff    24939 Jun 27  2014 music21-2.0.0/music21/webapps/archive/client/musescore/music21theoryAnalyzer/data/header.jpg
-rw-r--r--  0 cuthbert staff    24953 Jun 27  2014 music21-2.0.0/music21/webapps/archive/client/hackdaydemo/images/img2.jpg
-rw-r--r--  0 cuthbert staff    24953 Jun 27  2014 music21-2.0.0/music21/webapps/archive/client/hackdaydemo/img2.jpg
-rw-r--r--  0 cuthbert staff    25333 Jun 27  2014 music21-2.0.0/music21/webapps/archive/client/hackdaydemo/images/img1.jpg
-rw-r--r--  0 cuthbert staff    25333 Jun 27  2014 music21-2.0.0/music21/webapps/archive/client/hackdaydemo/img1.jpg
-rw-r--r--  0 cuthbert staff    26577 Jun 27  2014 music21-2.0.0/music21/webapps/archive/client/hackdaydemo/images/img4.jpg
-rw-r--r--  0 cuthbert staff    26577 Jun 27  2014 music21-2.0.0/music21/webapps/archive/client/hackdaydemo/img4.jpg
-rw-r--r--  0 cuthbert staff    26680 Jun 27  2014 music21-2.0.0/music21/webapps/archive/client/hackdaydemo/images/img6.jpg
-rw-r--r--  0 cuthbert staff    26680 Jun 27  2014 music21-2.0.0/music21/webapps/archive/client/hackdaydemo/img6.jpg
-rw-r--r--  0 cuthbert staff    31611 Jan  9 19:58 music21-2.0.0/music21/test/lastResults.txt
-rw-r--r--  0 cuthbert staff    43248 Jun 27  2014 music21-2.0.0/music21/webapps/archive/client/hackdaydemo/index.html
-rw-r--r--  0 cuthbert staff    60135 Dec 24 15:21 music21-2.0.0/music21/mei/test/test_file.pdf
-rw-r--r--  0 cuthbert staff    64767 Jun 27  2014 music21-2.0.0/music21/demos/bhadley/mrjobaws/allCorpusPaths.txt
-rw-r--r--  0 cuthbert staff    67422 Jun 27  2014 music21-2.0.0/music21/midi/testPrimitive/test04.mid
-rw-r--r--  0 cuthbert staff    85075 Jun 27  2014 music21-2.0.0/music21/ext/xlrd/doc/xlrd.html
-rw-r--r--  0 cuthbert staff  113030 Jun 27  2014 music21-2.0.0/music21/audioSearch/scores/d luca gloria_Page_4.tiff
-rw-r--r--  0 cuthbert staff  114906 Jun 27  2014 music21-2.0.0/music21/audioSearch/scores/d luca gloria_Page_3.tiff
-rw-r--r--  0 cuthbert staff  116308 Jun 27  2014 music21-2.0.0/music21/audioSearch/scores/d luca gloria_Page_2.tiff
-rw-r--r--  0 cuthbert staff  117122 Jun 27  2014 music21-2.0.0/music21/audioSearch/scores/d luca gloria_Page_5.tiff
-rw-r--r--  0 cuthbert staff   129909 Jun 27  2014 music21-2.0.0/music21/languageExcerpts/en.txt
-rw-r--r--  0 cuthbert staff   209406 Jun 27  2014 music21-2.0.0/music21/languageExcerpts/de.txt
-rw-r--r--  0 cuthbert staff   210203 Jun 27  2014 music21-2.0.0/music21/languageExcerpts/fr.txt
-rw-r--r--  0 cuthbert staff  334730 Jun 27  2014 music21-2.0.0/music21/audioSearch/scores/d luca gloria_Page_1.tiff
-rw-r--r--  0 cuthbert staff   346650 Jan 11 16:49 music21-2.0.0/music21.egg-info/SOURCES.txt
-rwxr-xr-x  0 cuthbert staff   422912 Jun 27  2014 music21-2.0.0/music21/trecento/cadences.xls
-rw-r--r--  0 cuthbert staff   570489 Jun 27  2014 music21-2.0.0/music21/languageExcerpts/cn.txt
-rw-r--r--  0 cuthbert staff   576611 Jun 27  2014 music21-2.0.0/music21/languageExcerpts/it.txt
-rw-r--r--  0 cuthbert staff 1763372 Jun 27  2014 music21-2.0.0/music21/audioSearch/test_audio.wav

**Comment by maxalbert** [comment]
I see. The size limit on PyPI makes this indeed tricky. To mitigate the problem, it would be helpful to have a note/warning prominently displayed, at least on the [PyPI page for music21](https://pypi.python.org/pypi/music21) and in the installation instructions, e.g. ["Automated Installation with pip"](http://web.mit.edu/music21/doc/installing/installAdvanced.html#automated-installation-with-pip) (not sure if this is also a problem with `easy_install`). Maybe it's even worth having a short note about this in the README.md file, since this is what is displayed on the [Github page](https://github.com/cuthbertLab/music21) and it takes two extra clicks to reach the installation instructions for pip, which many users who are familiar with pip won't bother reading because they think they can just use `pip install music21`?

**Comment by ahankinson** [comment]
From an developer's point of view, I find the size of music21 is starting to be a bit problematic as well. I realize that we're not the main audience so I understand why you want to keep the 'batteries included' on the main music21 repo. However, since we use music21 as a library to work on our own (non-m21-corpus) materials, it would be really handy to have a smaller 'music21 core' distribution available that we could add as in the `requirements.txt` to our applications. Maybe that could go up on PyPi? Perhaps an additional "install corpus" script could download the corpus from GitHub and install it to get the "full" installation? I would assume that if someone's installing something via `pip` then they're also capable of also typing in an additional `python install_corpus.py` command... Maybe I'm being naïve, though. :)

**Comment by maxalbert** [comment]
I don't know if there are any design choices or practicalities that would prevent this, but from a user's (and occasional contributor's) perspective splitting off the corpus as a separate package sounds like a good idea to me. It would reduce the size of the core package and might even allow contributions to the corpus from users who would otherwise shy away from development because they don't have enough programming experience. Also, I'm sure that the corpus would be useful to other music communities. From a brief look at the installation methods all of them seem to require at most one additional step to install the corpus as a separate package, provided the installation scripts are updated accordingly (but I may of course be missing something here).

**Comment by mscuthbert** [comment]
The main issue is fixed I believe... Thanks!  They upped the file size a bit and it's enough to get it in.

We can make splitting out the corpus be a separate item.  On the condition that it's downloaded on the first call to a corpus.parse().  As Andrew and others have noted, "batteries included" is one of the core principles of music21, so an included good corpus will always be a part of it.  The actual work in lowering the download size probably should come from trimming overly large images from the documentation or splitting that off somehow.
