### ISSUE TITLE
New Feature: Lewins in Post Tonal Tools

### ISSUE THREAD

**Issue by dandersen19** [cuthbertLab/music21#914]
**Feature Summary**
I propose adding a method that returns the "Lewins" for Fourier Balances 1-6 (given a chord, set, etc.) as described in Ian Quinn, "General Equal-Tempered Harmony," Perspectives of New Music 44/2 (2006) and 45/1 (2007). Lewins are vector magnitudes calculated through arrow addition of each pc in a given set. Each balance roughly correlates with a different intervallic or harmonic quality by assigning different angles to different pitch classes.

**Example of Current Functionality**
````
> get_lewins([0,1,2,3])
[3.3460652149512318, 1.732050807568877, 2.535772158592562e-16, 0.9999999999999994, 0.8965754721680536, 2.82842712474619]
````
Returns a list of Lewin values for each of the six Fourier Balances in order, given a set as list.

**Anticipated Functionality**
````
> c = chord.Chord([0, 1, 2, 3])
> c.lewins
[3.3460652149512318, 1.732050807568877, 2.535772158592562e-16, 0.9999999999999994, 0.8965754721680536, 2.82842712474619]
````

This would be my first contribution to music21. First I wanted to find out whether this of interest, and if so, what the next steps would be (e.g. wait for others to share improvements, or go ahead and start a pull request and conforming to music21 standards). Thanks!

**Code**

````
import math

def arrow_end_coords(angle):
   angle = math.radians(angle)
   x = math.cos(angle)
   y = math.sin(angle)
   coords = [x,y]
   return coords

def total_distance(all_angles):
   x = 0
   y = 0
   for i in all_angles:
      x = x + arrow_end_coords(i)[0]
      y = y + arrow_end_coords(i)[1]
   return math.sqrt(pow(x,2)+pow(y,2))

def get_lewins(pcset):

   pcset = [p % 12 for p in pcset] # convert to pc
   lewins = []

   lewins.append(total_distance([balance1[i] for i in pcset]))
   lewins.append(total_distance([balance2[i] for i in pcset]))
   lewins.append(total_distance([balance3[i] for i in pcset]))
   lewins.append(total_distance([balance4[i] for i in pcset]))
   lewins.append(total_distance([balance5[i] for i in pcset]))
   lewins.append(total_distance([balance6[i] for i in pcset]))

   return lewins

# pc angles for each balance

balance1 = {
   0: 90,
   1: 60,
   2: 30,
   3: 0,
   4: 330,
   5: 300,
   6: 270,
   7: 240,
   8: 210,
   9: 180,
   10: 150,
   11: 120
} 

balance2 = {
   0: 90,
   1: 30,
   2: 330,
   3: 270,
   4: 210,
   5: 150,
   6: 90,
   7: 30,
   8: 330,
   9: 270,
   10: 210,
   11: 150
} 

balance3 = {
   0: 90,
   1: 0,
   2: 270,
   3: 180,
   4: 90,
   5: 0,
   6: 270,
   7: 180,
   8: 90,
   9: 0,
   10: 270,
   11: 180
} 

balance4 = {
   0: 90,
   1: 330,
   2: 210,
   3: 90,
   4: 330,
   5: 210,
   6: 90,
   7: 330,
   8: 210,
   9: 90,
   10: 330,
   11: 210
} 

balance5 = {
   0: 90,
   1: 300,
   2: 150,
   3: 0,
   4: 210,
   5: 60,
   6: 270,
   7: 120,
   8: 330,
   9: 180,
   10: 30,
   11: 240
} 

balance6 = {
   0: 90,
   1: 180,
   2: 90,
   3: 180,
   4: 90,
   5: 180,
   6: 90,
   7: 180,
   8: 90,
   9: 180,
   10: 90,
   11: 180
} 
````

**Comment by jacobtylerwalls** [comment]
Hi, Drake, thanks for writing and for your interest in contributing. You likely know of Michael, one of the authors of the package. I'm not Michael! But I've been contributing, and in keeping with open-source project norms, I thought I'd chime in with a second opinion of a feature proposal.

At first glance, this seems a bit niche for the core package. If music21 had an ecosystem of third-party packages such as, say, Django has, we could say, "let's see some use in a third-party package" first. The audience for music21 is thinner--so the problem is that music21 core is probably the first and last place people look. But that's not a reason not to try to start this kind of ecosystem! From reading the mailing list I think there have been instances of announcing and sharing music21-derived packages. Another option for making a strong case for this addition would be asking for second opinions on the mailing list rather than GitHub. I recall your first message was (appropriately) asking about the mechanics of contributing, rather than more definitively asking list members to chime in with, "yes, I'd use that!"

Michael will chime in if he has different ideas, and I'm not ruling out saying yes to this. It's just that a "yes" might take a few months. I hope this makes sense.

PS -- if you did put together your own package, maybe you'd look into writing some feature extractors that could rank streams by Lewins. Now that would be food for a list thread.

**Comment by mscuthbert** [comment]
I think that a general rule should be usage in peer reviewed articles or semimajor book presses by at least two different authors (or three if the implementation is complex) before considering. 

These should go in an analysis module not directly on a major m21 object such as Chord unless they are completely standard in the field. See analysis.patel which has some of Ari Patel's algorithms that have become commonly used but not common enough to go on Stream. 

There are grandfathered in exceptions that shouldn't be the basis for a rule.

**Comment by jacobtylerwalls** [comment]
Michael's suggested rule makes sense to me. Thanks for your interest in contributing, Drake, as well as for the opportunity to form some of these guidelines for the first time. Feel free to follow up if you have a proposal in keeping with them. Cheers.

**Comment by dandersen19** [comment]
Thanks all for the clarifications and suggestions. Will do some thinking on this.
