### ISSUE TITLE
WindowedKey plot legend colors are all white

### ISSUE THREAD

**Issue by godofred** [cuthbertLab/music21#998]
**music21 version**

`6.7.1`   

**Problem summary**

When trying either of the examples of the Windowed Krumhansl-Schmuckler plot in the documentation, the color is white for all cells in the color grid for the legend.

**Steps to reproduce**
```
s = music21.corpus.parse('bach/bwv66.6')
s.plot('key')
```
or
```
s = music21.corpus.parse('bach/bwv66.6')
p = music21.graph.plot.WindowedKey(s.parts[0])
# p.processorClass = analysis.discrete.AardenEssen
# p.processorClass = analysis.discrete.SimpleWeights
# p.processorClass = analysis.discrete.BellmanBudge
# p.processorClass = analysis.discrete.TemperleyKostkaPayne
p.run()
```

**Expected vs. actual behavior**

Expected second image output:
![image](https://user-images.githubusercontent.com/9701505/116962243-d934c080-ac7b-11eb-83f1-52034a2d5fa4.png)

Actual second image output:
![image](https://user-images.githubusercontent.com/9701505/116962312-02555100-ac7c-11eb-8389-dd5b4d53e3a0.png)

**More information**

- Experimented on a local installation via Python Script on a Windows 10, and also via a Jupyter Notebook through Google Colab  both with default configuration. Same results in all combinations of environments, codes, and processorsClasses. Also tried a few different scores, which gave the same results.
- The actual plot image seems OK, at first glance - only the legend image is problematic.
- The number of grid cells changes for each different score, and seems to be correct (looking at the bwv66.6 example).

**Comment by jacobtylerwalls** [comment]
Verified. Thanks. PR shortly. While we're here, we need to update the user's guide example, because calling .plot('key') (windowed analysis) on a stream with parts will fail in v7 (#828). Solution is to call .flat or .parts.first().

Michael -- if you want to revisit that choice in #828, it would be as simple as copying the input stream and then doing a flat for the user -- just didn't want to leave destructive side effects on the input stream.
